Repository Clokey-dev/Clokey_SpringBoot, pull requests merged in 2025-01, with the labels that each got.

#2 [feat/#1] 프로젝트 세팅
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/clokey/server/ServerApplication.java
  src/main/java/com/clokey/server/global/common/response/BaseResponse.java
  src/main/java/com/clokey/server/global/config/SwaggerConfig.java
  src/main/java/com/clokey/server/global/config/security/SecurityConfig.java
  src/main/java/com/clokey/server/global/error/code/BaseCode.java
  src/main/java/com/clokey/server/global/error/code/BaseErrorCode.java
  src/main/java/com/clokey/server/global/error/code/ErrorReasonDTO.java
  src/main/java/com/clokey/server/global/error/code/ReasonDTO.java
  src/main/java/com/clokey/server/global/error/code/status/ErrorStatus.java
  src/main/java/com/clokey/server/global/error/code/status/SuccessStatus.java
  src/main/java/com/clokey/server/global/error/exception/GeneralException.java
  src/main/java/com/clokey/server/global/error/exception/GlobalExceptionAdvice.java
  src/main/resources/application.yml
  src/test/java/com/clokey/server/ServerApplicationTests.java
Labels: :sparkles: Feat

#6 [feat/#4] user, follow 도메인 추가
  src/main/java/com/clokey/server/domain/model/Follow.java
  src/main/java/com/clokey/server/domain/model/Member.java
  src/main/java/com/clokey/server/domain/model/enums/Gender.java
  src/main/java/com/clokey/server/domain/model/enums/MemberStatus.java
  src/main/java/com/clokey/server/domain/model/enums/SocialType.java
Labels: :sparkles: Feat

#7 [feat/#3] 옷 관련 도메인 생성
  src/main/java/com/clokey/server/domain/model/Cloth.java
  src/main/java/com/clokey/server/domain/model/ClothImage.java
  src/main/java/com/clokey/server/domain/model/enums/Visibility.java
Labels: :sparkles: Feat

#11 [Feat/#10] 매핑테이블 생성 및 엔티티 매핑 후 DB 생성
  .gitignore
  build.gradle
  src/main/java/com/clokey/server/ServerApplication.java
  src/main/java/com/clokey/server/domain/model/BaseEntity.java
  src/main/java/com/clokey/server/domain/model/Category.java
  src/main/java/com/clokey/server/domain/model/Cloth.java
  src/main/java/com/clokey/server/domain/model/History.java
  src/main/java/com/clokey/server/domain/model/Member.java
  src/main/java/com/clokey/server/domain/model/Term.java
  src/main/java/com/clokey/server/domain/model/enums/MemberStatus.java
  src/main/java/com/clokey/server/domain/model/mapping/ClothCategory.java
  src/main/java/com/clokey/server/domain/model/mapping/HistoryCloth.java
  src/main/java/com/clokey/server/domain/model/mapping/MemberAgree.java
  src/main/java/com/clokey/server/domain/model/mapping/MemberFollow.java
  src/main/java/com/clokey/server/domain/model/mapping/MemberLike.java
  src/main/java/com/clokey/server/global/config/PropertyConfig.java
Labels: :sparkles: Feat

#15 [feat/#12] ApiResponse 세팅 및 응답 코드 세팅
  src/main/java/com/clokey/server/domain/ClothFolder/application/ClothFolderRepositoryService.java
  src/main/java/com/clokey/server/domain/ClothFolder/application/ClothFolderRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/ClothFolder/dao/ClothFolderRepository.java
  src/main/java/com/clokey/server/domain/ClothImage/dao/ClothImageRepository.java
  src/main/java/com/clokey/server/domain/HashtagHistory/dao/HashtagHistoryRepository.java
  src/main/java/com/clokey/server/domain/HistoryCloth/dao/HistoryClothRepository.java
  src/main/java/com/clokey/server/domain/HistoryImage/dao/HistoryImageRepository.java
  src/main/java/com/clokey/server/domain/MemberLike/dao/MemberLikeRepository.java
  src/main/java/com/clokey/server/domain/MemberTerm/dao/MemberTermRepository.java
  src/main/java/com/clokey/server/domain/category/application/CategoryRepositoryService.java
  src/main/java/com/clokey/server/domain/category/application/CategoryRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/category/dao/CategoryRepository.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothRepositoryService.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/cloth/dao/ClothRepository.java
  src/main/java/com/clokey/server/domain/comment/application/CommentRepositoryService.java
  src/main/java/com/clokey/server/domain/comment/application/CommentRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/comment/dao/CommentRepository.java
  src/main/java/com/clokey/server/domain/folder/application/FolderRepositoryImpl.java
  src/main/java/com/clokey/server/domain/folder/application/FolderRepositoryService.java
  src/main/java/com/clokey/server/domain/folder/dao/FolderRepository.java
  src/main/java/com/clokey/server/domain/follow/dao/FollowRepository.java
  src/main/java/com/clokey/server/domain/hashtag/dao/HashtagRepository.java
  src/main/java/com/clokey/server/domain/history/application/HistoryRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/dao/HistoryRepository.java
  src/main/java/com/clokey/server/domain/member/application/MemberRepositoryService.java
  src/main/java/com/clokey/server/domain/member/application/MemberRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/member/dao/MemberRepository.java
  src/main/java/com/clokey/server/domain/model/Cloth.java
  src/main/java/com/clokey/server/domain/model/Follow.java
  src/main/java/com/clokey/server/domain/model/History.java
  src/main/java/com/clokey/server/domain/model/Member.java
  src/main/java/com/clokey/server/domain/model/Notification.java
  src/main/java/com/clokey/server/domain/model/Term.java
  src/main/java/com/clokey/server/domain/model/enums/NotificationType.java
  src/main/java/com/clokey/server/domain/model/enums/SummaryFrequency.java
  src/main/java/com/clokey/server/domain/model/mapping/Follow.java
  src/main/java/com/clokey/server/domain/model/mapping/MemberTerm.java
  src/main/java/com/clokey/server/domain/notification/dao/NotificationRepository.java
  src/main/java/com/clokey/server/domain/term/application/TermRepositoryService.java
  src/main/java/com/clokey/server/domain/term/application/TermRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/term/dao/TermRepository.java
  src/main/java/com/clokey/server/global/common/response/BaseResponse.java
  src/main/java/com/clokey/server/global/error/code/ReasonDTO.java
  src/main/java/com/clokey/server/global/error/code/status/ErrorStatus.java
  src/main/java/com/clokey/server/global/error/code/status/SuccessStatus.java
Labels: :sparkles: Feat

#20 [feat/#19] 폴더 생성 API 구현
  build.gradle
  src/main/java/com/clokey/server/domain/folder/api/FolderController.java
  src/main/java/com/clokey/server/domain/folder/application/FolderRepositoryService.java
  src/main/java/com/clokey/server/domain/folder/application/FolderRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/folder/application/FolderService.java
  src/main/java/com/clokey/server/domain/folder/application/FolderServiceImpl.java
  src/main/java/com/clokey/server/domain/folder/converter/FolderConverter.java
  src/main/java/com/clokey/server/domain/folder/dto/FolderRequest.java
  src/main/java/com/clokey/server/domain/folder/dto/FolderResponse.java
  src/main/java/com/clokey/server/domain/member/application/MemberRepositoryService.java
  src/main/java/com/clokey/server/domain/member/application/MemberRepositoryServiceImpl.java
  src/main/java/com/clokey/server/global/config/security/SecurityConfig.java
Labels: :sparkles: Feat

#29 [feat/#17] 기록 월/일 별 조회 기능 구현
  build.gradle
  src/main/java/com/clokey/server/domain/HashtagHistory/application/HashtagHistoryRepositoryService.java
  src/main/java/com/clokey/server/domain/HashtagHistory/application/HashtagHistoryRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/HashtagHistory/dao/HashtagHistoryRepository.java
  src/main/java/com/clokey/server/domain/HistoryImage/application/HistoryImageRepositoryService.java
  src/main/java/com/clokey/server/domain/HistoryImage/application/HistoryImageRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/HistoryImage/dao/HistoryImageRepository.java
  src/main/java/com/clokey/server/domain/MemberLike/application/MemberLikeRepositoryService.java
  src/main/java/com/clokey/server/domain/MemberLike/application/MemberLikeRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/MemberLike/dao/MemberLikeRepository.java
  src/main/java/com/clokey/server/domain/history/api/HistoryRestController.java
  src/main/java/com/clokey/server/domain/history/application/HistoryRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/converter/HistoryConverter.java
  src/main/java/com/clokey/server/domain/history/dao/HistoryRepository.java
  src/main/java/com/clokey/server/domain/history/dto/HistoryResponseDto.java
  src/main/java/com/clokey/server/domain/history/exception/annotation/HistoryExist.java
  src/main/java/com/clokey/server/domain/history/exception/annotation/MonthFormat.java
  src/main/java/com/clokey/server/domain/history/exception/validator/HistoryAccessibleValidator.java
  src/main/java/com/clokey/server/domain/history/exception/validator/HistoryExistValidator.java
  src/main/java/com/clokey/server/domain/history/exception/validator/MonthFormatValidator.java
  src/main/java/com/clokey/server/domain/member/application/MemberRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/member/exception/annotation/MemberExist.java
  src/main/java/com/clokey/server/domain/member/exception/validator/MemberExistValidator.java
  src/main/java/com/clokey/server/global/error/code/status/ErrorStatus.java
  src/main/java/com/clokey/server/global/error/code/status/SuccessStatus.java
Labels: :sparkles: Feat

#28 [feat/#27] 프로필 수정 api 생성
  src/main/java/com/clokey/server/domain/folder/application/FolderRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/member/api/ProfileRestController.java
  src/main/java/com/clokey/server/domain/member/application/MemberRepositoryService.java
  src/main/java/com/clokey/server/domain/member/application/MemberRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/member/application/ProfileCommandService.java
  src/main/java/com/clokey/server/domain/member/application/ProfileCommandServiceImpl.java
  src/main/java/com/clokey/server/domain/member/converter/ProfileConverter.java
  src/main/java/com/clokey/server/domain/member/dto/ProfileRequestDTO.java
  src/main/java/com/clokey/server/domain/member/dto/ProfileResponseDTO.java
  src/main/java/com/clokey/server/domain/member/exception/MemberException.java
  src/main/java/com/clokey/server/domain/model/Member.java
  src/main/java/com/clokey/server/global/error/code/status/SuccessStatus.java
Labels: :sparkles: Feat

#33 [Feat/#32] 댓글 조회 기능 구현
  src/main/java/com/clokey/server/domain/comment/application/CommentRepositoryService.java
  src/main/java/com/clokey/server/domain/comment/application/CommentRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/comment/dao/CommentRepository.java
  src/main/java/com/clokey/server/domain/history/api/HistoryRestController.java
  src/main/java/com/clokey/server/domain/history/application/HistoryRepositoryService.java
  src/main/java/com/clokey/server/domain/history/converter/HistoryConverter.java
  src/main/java/com/clokey/server/domain/history/dto/HistoryResponseDto.java
  src/main/java/com/clokey/server/domain/history/exception/annotation/CheckPage.java
  src/main/java/com/clokey/server/domain/history/exception/validator/CheckPageValidator.java
  src/main/java/com/clokey/server/global/error/code/status/ErrorStatus.java
Labels: :sparkles: Feat

#31 [feat/#30] 기록 좋아요 API 구현
  src/main/java/com/clokey/server/domain/MemberLike/application/MemberLikeRepositoryService.java
  src/main/java/com/clokey/server/domain/MemberLike/application/MemberLikeRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/MemberLike/dao/MemberLikeRepository.java
  src/main/java/com/clokey/server/domain/history/api/HistoryRestController.java
  src/main/java/com/clokey/server/domain/history/application/HistoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/converter/HistoryConverter.java
  src/main/java/com/clokey/server/domain/history/dao/HistoryRepository.java
  src/main/java/com/clokey/server/domain/history/dto/HistoryRequestDto.java
  src/main/java/com/clokey/server/domain/history/dto/HistoryResponseDto.java
  src/main/java/com/clokey/server/domain/history/exception/annotation/HistoryExist.java
  src/main/java/com/clokey/server/domain/history/exception/validator/HistoryLikedValidator.java
  src/main/java/com/clokey/server/domain/model/History.java
  src/main/java/com/clokey/server/domain/model/mapping/MemberLike.java
  src/main/java/com/clokey/server/global/error/code/status/SuccessStatus.java
  src/main/java/com/clokey/server/global/error/exception/GlobalExceptionAdvice.java
Labels: :sparkles: Feat

#37 [fix/#14] 충돌 오류 사항 수정 완료
  src/main/java/com/clokey/server/domain/history/api/HistoryRestController.java
  src/main/java/com/clokey/server/domain/history/converter/HistoryConverter.java
  src/main/java/com/clokey/server/domain/history/dto/HistoryResponseDto.java
  src/main/java/com/clokey/server/domain/member/application/MemberRepositoryServiceImpl.java
Labels: :fire: Fix

#26 [feat/#25] 약관동의 api 구현
  src/main/java/com/clokey/server/domain/MemberTerm/application/MemberTermRepositoryService.java
  src/main/java/com/clokey/server/domain/MemberTerm/application/MemberTermRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/member/application/MemberRepositoryService.java
  src/main/java/com/clokey/server/domain/member/application/MemberRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/term/api/TermRestController.java
  src/main/java/com/clokey/server/domain/term/application/TermCommandService.java
  src/main/java/com/clokey/server/domain/term/application/TermCommandServiceImpl.java
  src/main/java/com/clokey/server/domain/term/application/TermRepositoryService.java
  src/main/java/com/clokey/server/domain/term/application/TermRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/term/converter/TermConverter.java
  src/main/java/com/clokey/server/domain/term/dto/TermRequestDTO.java
  src/main/java/com/clokey/server/domain/term/dto/TermResponseDTO.java
  src/main/java/com/clokey/server/domain/term/exception/TermException.java
Labels: :sparkles: Feat

#24 [feat/#18] 카테고리 조회 api 구현
  build.gradle
  src/main/java/com/clokey/server/domain/category/api/CategoryRestController.java
  src/main/java/com/clokey/server/domain/category/application/CategoryQueryService.java
  src/main/java/com/clokey/server/domain/category/application/CategoryQueryServiceImpl.java
  src/main/java/com/clokey/server/domain/category/application/CategoryRepositoryService.java
  src/main/java/com/clokey/server/domain/category/application/CategoryRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/category/converter/CategoryConverter.java
  src/main/java/com/clokey/server/domain/category/dto/CategoryResponseDTO.java
  src/main/java/com/clokey/server/domain/folder/application/FolderRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/folder/dao/FolderRepository.java
  src/main/java/com/clokey/server/domain/model/Member.java
  src/main/java/com/clokey/server/domain/term/dto/TermsRequestDTO.java
  src/main/java/com/clokey/server/domain/term/dto/TermsResponseDTO.java
  src/main/resources/application.yml
  src/main/resources/properties/env.properties
  src/main/resources/properties/properties.env
Labels: :sparkles: Feat

#38 [feat/#35] 아이디 중복 확인 api 생성
  build.gradle
  src/main/java/com/clokey/server/domain/history/api/HistoryRestController.java
  src/main/java/com/clokey/server/domain/member/api/IDRestController.java
  src/main/java/com/clokey/server/domain/member/api/ProfileRestController.java
  src/main/java/com/clokey/server/domain/member/application/IDQueryService.java
  src/main/java/com/clokey/server/domain/member/application/IDQueryServiceImpl.java
  src/main/java/com/clokey/server/domain/member/application/MemberRepositoryService.java
  src/main/java/com/clokey/server/domain/member/application/MemberRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/member/application/ProfileCommandService.java
  src/main/java/com/clokey/server/domain/member/application/ProfileCommandServiceImpl.java
  src/main/java/com/clokey/server/domain/member/converter/IDConverter.java
  src/main/java/com/clokey/server/domain/member/converter/ProfileConverter.java
  src/main/java/com/clokey/server/domain/member/dao/MemberRepository.java
  src/main/java/com/clokey/server/domain/member/dto/IDRequestDTO.java
  src/main/java/com/clokey/server/domain/member/dto/IDResponseDTO.java
  src/main/java/com/clokey/server/domain/member/dto/ProfileRequestDTO.java
  src/main/java/com/clokey/server/domain/member/dto/ProfileResponseDTO.java
  src/main/java/com/clokey/server/domain/member/exception/annotation/IdExist.java
  src/main/java/com/clokey/server/domain/member/exception/validator/IdExistValidator.java
  src/main/java/com/clokey/server/global/error/code/status/SuccessStatus.java
Labels: :sparkles: Feat

#44 [feat/#32] 댓글 작성 API
  .gitignore
  src/main/java/com/clokey/server/domain/comment/application/CommentRepositoryService.java
  src/main/java/com/clokey/server/domain/comment/application/CommentRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/comment/dao/CommentRepository.java
  src/main/java/com/clokey/server/domain/history/api/HistoryRestController.java
  src/main/java/com/clokey/server/domain/history/application/HistoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/converter/HistoryConverter.java
  src/main/java/com/clokey/server/domain/history/dto/HistoryRequestDto.java
  src/main/java/com/clokey/server/domain/history/dto/HistoryResponseDto.java
  src/main/java/com/clokey/server/domain/history/exception/annotation/ContentLength.java
  src/main/java/com/clokey/server/domain/history/exception/annotation/ParentCommentConditions.java
  src/main/java/com/clokey/server/domain/history/exception/validator/CommentValidator.java
  src/main/java/com/clokey/server/domain/history/exception/validator/ContentLengthValidator.java
  src/main/java/com/clokey/server/domain/history/exception/validator/ParentCommentsConditionsValidator.java
  src/main/java/com/clokey/server/global/error/code/status/ErrorStatus.java
  src/main/java/com/clokey/server/global/error/code/status/SuccessStatus.java
  src/main/resources/properties/env.properties
  src/main/resources/properties/properties.env
Labels: :sparkles: Feat

#48 [fix/#47] gitignore 수정
  .gitignore
Labels: :fire: Fix

#45 [feat/#41] 회원 조회 api 구현
  src/main/java/com/clokey/server/domain/category/api/CategoryRestController.java
  src/main/java/com/clokey/server/domain/category/application/CategoryQueryService.java
  src/main/java/com/clokey/server/domain/category/application/CategoryQueryServiceImpl.java
  src/main/java/com/clokey/server/domain/category/converter/CategoryConverter.java
  src/main/java/com/clokey/server/domain/category/dto/CategoryResponseDTO.java
  src/main/java/com/clokey/server/domain/member/api/IDRestController.java
  src/main/java/com/clokey/server/domain/member/api/MemberRestController.java
  src/main/java/com/clokey/server/domain/member/api/ProfileRestController.java
  src/main/java/com/clokey/server/domain/member/application/GetUserQueryService.java
  src/main/java/com/clokey/server/domain/member/application/GetUserQueryServiceImpl.java
  src/main/java/com/clokey/server/domain/member/application/IDQueryService.java
  src/main/java/com/clokey/server/domain/member/application/IDQueryServiceImpl.java
  src/main/java/com/clokey/server/domain/member/application/MemberRepositoryService.java
  src/main/java/com/clokey/server/domain/member/application/MemberRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/member/application/ProfileCommandService.java
  src/main/java/com/clokey/server/domain/member/application/ProfileCommandServiceImpl.java
  src/main/java/com/clokey/server/domain/member/converter/GetUserConverter.java
  src/main/java/com/clokey/server/domain/member/converter/IDConverter.java
  src/main/java/com/clokey/server/domain/member/converter/ProfileConverter.java
  src/main/java/com/clokey/server/domain/member/dto/IDRequestDTO.java
  src/main/java/com/clokey/server/domain/member/dto/IDResponseDTO.java
  src/main/java/com/clokey/server/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/clokey/server/domain/member/dto/ProfileRequestDTO.java
  src/main/java/com/clokey/server/domain/member/dto/ProfileResponseDTO.java
  src/main/java/com/clokey/server/domain/member/exception/annotation/EssentialFieldNotNull.java
  src/main/java/com/clokey/server/domain/member/exception/annotation/IdValid.java
  src/main/java/com/clokey/server/domain/member/exception/validator/EssentialFieldNotNullValidator.java
  src/main/java/com/clokey/server/domain/member/exception/validator/IdExistValidator.java
  src/main/java/com/clokey/server/domain/member/exception/validator/IdValidValidator.java
  src/main/java/com/clokey/server/domain/term/api/TermRestController.java
  src/main/java/com/clokey/server/domain/term/application/TermCommandService.java
  src/main/java/com/clokey/server/domain/term/application/TermCommandServiceImpl.java
  src/main/java/com/clokey/server/domain/term/converter/TermConverter.java
  src/main/java/com/clokey/server/domain/term/dto/TermRequestDTO.java
  src/main/java/com/clokey/server/domain/term/dto/TermResponseDTO.java
  src/main/java/com/clokey/server/domain/term/dto/TermsRequestDTO.java
  src/main/java/com/clokey/server/domain/term/dto/TermsResponseDTO.java
  src/main/java/com/clokey/server/domain/term/exception/annotation/EssentialTermAgree.java
  src/main/java/com/clokey/server/domain/term/exception/validator/EssentialTermAgreeValidator.java
Labels: :sparkles: Feat

#59 [file/#58] propertyConfig 삭제
  src/main/java/com/clokey/server/global/config/PropertyConfig.java
Labels: :fire: Fix

#68 [feat/#66] 옷 삭제 API 구현
  src/main/java/com/clokey/server/ServerApplication.java
  src/main/java/com/clokey/server/domain/cloth/api/ClothRestController.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothService.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothServiceImpl.java
  src/main/java/com/clokey/server/domain/cloth/converter/ClothConverter.java
  src/main/java/com/clokey/server/domain/cloth/dto/ClothRequestDto.java
  src/main/java/com/clokey/server/domain/cloth/dto/ClothResponseDto.java
  src/main/java/com/clokey/server/domain/cloth/exception/annotation/ClothExist.java
  src/main/java/com/clokey/server/domain/cloth/exception/validator/ClothAccessibleValidator.java
  src/main/java/com/clokey/server/domain/cloth/exception/validator/ClothExistValidator.java
  src/main/java/com/clokey/server/domain/model/entity/Cloth.java
  src/main/java/com/clokey/server/domain/model/entity/Notification.java
  src/main/java/com/clokey/server/domain/model/entity/enums/ThicknessLevel.java
  src/main/java/com/clokey/server/domain/model/repository/ClothFolderRepository.java
  src/main/java/com/clokey/server/domain/model/repository/ClothImageRepository.java
  src/main/java/com/clokey/server/domain/model/repository/ClothRepository.java
  src/main/java/com/clokey/server/domain/model/repository/HistoryClothRepository.java
  src/main/java/com/clokey/server/global/error/code/status/SuccessStatus.java
Labels: :sparkles: Feat

#71 [feat/#70] S3 연동 추가
  build.gradle
  src/main/java/com/clokey/server/global/error/code/status/ErrorStatus.java
  src/main/java/com/clokey/server/global/infra/s3/S3ImageService.java
  src/main/java/com/clokey/server/global/infra/s3/S3ImageServiceImpl.java
  src/main/java/com/clokey/server/global/infra/s3/config/S3Config.java
  src/main/java/com/clokey/server/global/infra/s3/exception/S3Exception.java
  src/main/resources/application.yml
Labels: :sparkles: Feat

#74 [feat/#23] 폴더명 수정 api
  src/main/java/com/clokey/server/domain/folder/api/FolderRestController.java
  src/main/java/com/clokey/server/domain/folder/application/FolderService.java
  src/main/java/com/clokey/server/domain/folder/application/FolderServiceImpl.java
  src/main/java/com/clokey/server/domain/folder/converter/FolderConverter.java
  src/main/java/com/clokey/server/domain/folder/dto/FolderRequest.java
  src/main/java/com/clokey/server/domain/folder/dto/FolderRequestDTO.java
  src/main/java/com/clokey/server/domain/folder/dto/FolderResponseDTO.java
  src/main/java/com/clokey/server/domain/folder/exception/FolderException.java
  src/main/java/com/clokey/server/domain/folder/exception/annotation/FolderExist.java
  src/main/java/com/clokey/server/domain/folder/exception/validator/FolderExistValidator.java
  src/main/java/com/clokey/server/domain/model/entity/Folder.java
  src/main/java/com/clokey/server/global/error/code/status/SuccessStatus.java
Labels: :sparkles: Feat

#73 [feat/#69] 옷 조회 API 관련 리팩토링
  src/main/java/com/clokey/server/domain/cloth/api/ClothRestController.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothService.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothServiceImpl.java
  src/main/java/com/clokey/server/domain/cloth/converter/ClothConverter.java
  src/main/java/com/clokey/server/domain/cloth/dto/ClothRequestDTO.java
  src/main/java/com/clokey/server/domain/cloth/dto/ClothResponseDTO.java
  src/main/java/com/clokey/server/domain/cloth/exception/ClothException.java
  src/main/java/com/clokey/server/domain/cloth/exception/validator/ClothAccessibleValidator.java
  src/main/java/com/clokey/server/domain/cloth/exception/validator/ClothExistValidator.java
  src/main/java/com/clokey/server/domain/model/entity/Cloth.java
  src/main/java/com/clokey/server/domain/model/repository/MemberRepository.java
Labels: :recycle: Refactor

#72 feat/#60 블루 그린 배포
  .github/workflows/dev_deploy.yml
  .gitignore
  Dockerfile
  build.gradle
  docker-compose.yml
  src/main/java/com/clokey/server/ServerApplication.java
  src/main/java/com/clokey/server/global/infra/s3/S3ImageServiceImpl.java
  src/main/java/com/clokey/server/global/infra/s3/config/S3Config.java
  src/main/resources/application.yml
Labels: :sparkles: Feat

#78 [feat/#63] 옷 생성 API 구현
  build.gradle
  src/main/java/com/clokey/server/domain/cloth/api/ClothRestController.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothService.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothServiceImpl.java
  src/main/java/com/clokey/server/domain/cloth/converter/ClothConverter.java
  src/main/java/com/clokey/server/domain/cloth/dto/ClothRequestDTO.java
  src/main/java/com/clokey/server/global/infra/s3/MultipartJackson2HttpMessageConverter.java
  src/main/java/com/clokey/server/global/infra/s3/config/S3Config.java
  src/main/resources/application.yml
Labels: :sparkles: Feat

#83 [Feat/#82] 기록 추가 API 구현
  src/main/java/com/clokey/server/domain/cloth/api/ClothRestController.java
  src/main/java/com/clokey/server/domain/cloth/domain/entity/Cloth.java
  src/main/java/com/clokey/server/domain/cloth/exception/validator/ClothAccessibleValidator.java
  src/main/java/com/clokey/server/domain/history/api/HistoryRestController.java
  src/main/java/com/clokey/server/domain/history/application/HashtagHistoryRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HashtagHistoryRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HashtagRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HashtagRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HistoryClothRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryClothRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HistoryImageRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryImageRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HistoryRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HistoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/converter/HistoryConverter.java
  src/main/java/com/clokey/server/domain/history/domain/repository/HashtagRepository.java
  src/main/java/com/clokey/server/domain/history/domain/repository/HistoryRepository.java
  src/main/java/com/clokey/server/domain/history/dto/HistoryRequestDTO.java
  src/main/java/com/clokey/server/domain/history/dto/HistoryResponseDTO.java
  src/main/java/com/clokey/server/domain/history/exception/HashtagException.java
  src/main/java/com/clokey/server/domain/history/exception/HistoryException.java
  src/main/java/com/clokey/server/domain/history/exception/annotation/CommentContentLength.java
  src/main/java/com/clokey/server/domain/history/exception/annotation/HistoryContentLength.java
  src/main/java/com/clokey/server/domain/history/exception/annotation/HistoryDateFormat.java
  src/main/java/com/clokey/server/domain/history/exception/annotation/HistoryImageQuantityLimit.java
  src/main/java/com/clokey/server/domain/history/exception/annotation/UniqueClothes.java
  src/main/java/com/clokey/server/domain/history/exception/annotation/UniqueHashtags.java
  src/main/java/com/clokey/server/domain/history/exception/validator/CommentContentLengthValidator.java
  src/main/java/com/clokey/server/domain/history/exception/validator/HistoryAlreadyExistValidator.java
  src/main/java/com/clokey/server/domain/history/exception/validator/HistoryContentLengthValidator.java
  src/main/java/com/clokey/server/domain/history/exception/validator/HistoryDateFormatValidator.java
  src/main/java/com/clokey/server/domain/history/exception/validator/HistoryImageQuantityLimitValidator.java
  src/main/java/com/clokey/server/domain/history/exception/validator/UniqueClothesValidator.java
  src/main/java/com/clokey/server/domain/history/exception/validator/UniqueHashtagsValidator.java
  src/main/java/com/clokey/server/global/error/code/status/ErrorStatus.java
Labels: :sparkles: Feat

#87 [Feat/#85] 기록을 업데이트 하는 API
  src/main/java/com/clokey/server/domain/cloth/exception/validator/ClothAccessibleValidator.java
  src/main/java/com/clokey/server/domain/history/api/HistoryRestController.java
  src/main/java/com/clokey/server/domain/history/application/HashtagHistoryRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HashtagHistoryRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HistoryClothRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryClothRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HistoryImageRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryImageRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HistoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/domain/entity/History.java
  src/main/java/com/clokey/server/domain/history/domain/repository/HashtagHistoryRepository.java
  src/main/java/com/clokey/server/domain/history/domain/repository/HistoryClothRepository.java
  src/main/java/com/clokey/server/domain/history/domain/repository/HistoryRepository.java
  src/main/java/com/clokey/server/domain/history/dto/HistoryRequestDTO.java
  src/main/java/com/clokey/server/domain/history/exception/validator/HistoryAccessibleValidator.java
  src/main/java/com/clokey/server/global/error/code/status/ErrorStatus.java
  src/main/java/com/clokey/server/global/error/code/status/SuccessStatus.java
Labels: :sparkles: Feat

#86 [feat/#67&#84] 옷 수정 API 구현 및 옷 팝업용/수정용/관리자용 조회 API 구현
  src/main/java/com/clokey/server/domain/cloth/api/ClothRestController.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothImageRepositoryService.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothImageRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothService.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothServiceImpl.java
  src/main/java/com/clokey/server/domain/cloth/converter/ClothConverter.java
  src/main/java/com/clokey/server/domain/cloth/domain/entity/Cloth.java
  src/main/java/com/clokey/server/domain/cloth/domain/entity/ClothImage.java
  src/main/java/com/clokey/server/domain/cloth/domain/repository/ClothImageRepository.java
  src/main/java/com/clokey/server/domain/cloth/domain/repository/ClothRepository.java
  src/main/java/com/clokey/server/domain/cloth/dto/ClothRequestDTO.java
  src/main/java/com/clokey/server/domain/cloth/dto/ClothResponseDTO.java
  src/main/java/com/clokey/server/domain/history/application/HistoryClothRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryClothRepositoryServiceImpl.java
  src/main/java/com/clokey/server/global/error/code/status/SuccessStatus.java
Labels: :sparkles: Feat

#89 [Feat/#88] 댓글 수정/삭제 API 구현
  src/main/java/com/clokey/server/domain/history/api/HistoryRestController.java
  src/main/java/com/clokey/server/domain/history/application/CommentRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/CommentRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HistoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/domain/entity/Comment.java
  src/main/java/com/clokey/server/domain/history/domain/repository/CommentRepository.java
  src/main/java/com/clokey/server/domain/history/dto/HistoryRequestDTO.java
  src/main/java/com/clokey/server/global/error/code/status/ErrorStatus.java
  src/main/java/com/clokey/server/global/error/code/status/SuccessStatus.java
Labels: :sparkles: Feat

#91 [Feat/#90] 작년의 오늘 기록 조회 API 구현 완료
  src/main/java/com/clokey/server/domain/history/api/HistoryRestController.java
  src/main/java/com/clokey/server/domain/history/application/HistoryImageRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HistoryRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HistoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/converter/HistoryConverter.java
  src/main/java/com/clokey/server/domain/history/domain/repository/HistoryRepository.java
  src/main/java/com/clokey/server/domain/history/dto/HistoryResponseDTO.java
  src/main/java/com/clokey/server/global/error/code/status/ErrorStatus.java
Labels: :sparkles: Feat

#93 [Feat/#92] 기록 삭제 API 구현
  .github/workflows/dev_deploy.yml
  src/main/java/com/clokey/server/domain/history/api/HistoryRestController.java
  src/main/java/com/clokey/server/domain/history/application/CommentRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/CommentRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HashtagHistoryRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HashtagHistoryRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HistoryClothRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryClothRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HistoryRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HistoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/MemberLikeRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/MemberLikeRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/domain/repository/CommentRepository.java
  src/main/java/com/clokey/server/domain/history/domain/repository/HashtagHistoryRepository.java
  src/main/java/com/clokey/server/domain/history/domain/repository/HistoryClothRepository.java
  src/main/java/com/clokey/server/domain/history/domain/repository/MemberLikeRepository.java
  src/main/java/com/clokey/server/domain/notification/domain/entity/Notification.java
  src/main/java/com/clokey/server/global/error/code/status/SuccessStatus.java
Labels: :sparkles: Feat

#96 [refactor/#94] 코드 리펙토링 및 버그 해결
  .github/workflows/dev_deploy.yml
  src/main/java/com/clokey/server/domain/cloth/application/ClothRepositoryService.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/api/HistoryRestController.java
  src/main/java/com/clokey/server/domain/history/application/HashtagHistoryRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HashtagHistoryRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HashtagRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HashtagRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HistoryClothRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryClothRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HistoryImageRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryImageRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HistoryRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HistoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/converter/HistoryConverter.java
  src/main/java/com/clokey/server/domain/history/domain/repository/HashtagHistoryRepository.java
  src/main/java/com/clokey/server/domain/history/domain/repository/HashtagRepository.java
  src/main/java/com/clokey/server/domain/history/domain/repository/HistoryClothRepository.java
  src/main/java/com/clokey/server/domain/history/dto/HistoryResponseDTO.java
  src/main/java/com/clokey/server/domain/history/exception/validator/CommentValidator.java
  src/main/java/com/clokey/server/domain/member/exception/annotation/NullableMemberExist.java
  src/main/java/com/clokey/server/domain/member/exception/validator/NullableMemberExistValidator.java
Labels: :recycle: Refactor

#99 [refactor/#97] api improve
  src/main/java/com/clokey/server/domain/member/application/ProfileCommandServiceImpl.java
  src/main/java/com/clokey/server/domain/member/converter/GetUserConverter.java
  src/main/java/com/clokey/server/domain/member/converter/ProfileConverter.java
  src/main/java/com/clokey/server/domain/member/domain/entity/Member.java
  src/main/java/com/clokey/server/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/clokey/server/domain/model/entity/enums/RegisterStatus.java
  src/main/java/com/clokey/server/domain/term/application/TermCommandServiceImpl.java
  src/main/java/com/clokey/server/domain/term/domain/entity/Term.java
  src/main/java/com/clokey/server/domain/term/dto/TermRequestDTO.java
  src/main/java/com/clokey/server/domain/term/exception/annotation/EssentialTermAgree.java
  src/main/java/com/clokey/server/domain/term/exception/validator/EssentialTermAgreeValidator.java
Labels: :recycle: Refactor

#101 [feat/#75] 폴더에 옷 추가 API 구현
  src/main/java/com/clokey/server/domain/folder/api/FolderRestController.java
  src/main/java/com/clokey/server/domain/folder/application/ClothFolderRepositoryService.java
  src/main/java/com/clokey/server/domain/folder/application/ClothFolderRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/folder/application/FolderRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/folder/application/FolderService.java
  src/main/java/com/clokey/server/domain/folder/application/FolderServiceImpl.java
  src/main/java/com/clokey/server/domain/folder/domain/entity/ClothFolder.java
  src/main/java/com/clokey/server/domain/folder/domain/repository/ClothFolderRepository.java
  src/main/java/com/clokey/server/domain/folder/domain/repository/FolderRepository.java
  src/main/java/com/clokey/server/domain/folder/dto/FolderRequestDTO.java
  src/main/java/com/clokey/server/domain/folder/exception/validator/FolderAccessibleValidator.java
  src/main/java/com/clokey/server/global/error/code/status/ErrorStatus.java
  src/main/java/com/clokey/server/global/error/code/status/SuccessStatus.java
Labels: :sparkles: Feat, :recycle: Refactor

#103 [feat/#102] 토큰에서 정보 추출 어노테이션 구현
  src/main/java/com/clokey/server/domain/history/api/HistoryRestController.java
  src/main/java/com/clokey/server/domain/member/application/AuthServiceImpl.java
  src/main/java/com/clokey/server/domain/member/domain/entity/Member.java
  src/main/java/com/clokey/server/domain/member/exception/annotation/AuthUser.java
  src/main/java/com/clokey/server/domain/member/exception/validator/AuthUserArgumentResolver.java
  src/main/java/com/clokey/server/global/config/WebConfig.java
  src/main/java/com/clokey/server/global/config/security/SecurityConfig.java
  src/main/java/com/clokey/server/global/config/security/auth/PrincipalDetails.java
  src/main/java/com/clokey/server/global/config/security/auth/PrincipalDetailsService.java
  src/main/java/com/clokey/server/global/config/security/jwt/JwtConfig.java
  src/main/java/com/clokey/server/global/config/security/jwt/JwtRequestFilter.java
Labels: :sparkles: Feat, :recycle: Refactor

#105 [refactor/#100] 기능 수정사항 반영
  src/main/java/com/clokey/server/domain/history/api/HistoryRestController.java
  src/main/java/com/clokey/server/domain/history/application/HistoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/MemberLikeRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/MemberLikeRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/converter/HistoryConverter.java
  src/main/java/com/clokey/server/domain/history/domain/repository/MemberLikeRepository.java
  src/main/java/com/clokey/server/domain/history/dto/HistoryResponseDTO.java
  src/main/java/com/clokey/server/domain/member/application/FollowRepositoryService.java
  src/main/java/com/clokey/server/domain/member/application/FollowRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/member/application/MemberRepositoryService.java
  src/main/java/com/clokey/server/domain/member/application/MemberRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/member/domain/repository/FollowRepository.java
  src/main/java/com/clokey/server/domain/member/domain/repository/MemberRepository.java
  src/main/java/com/clokey/server/domain/member/exception/annotation/NullableClokeyIdExist.java
  src/main/java/com/clokey/server/domain/member/exception/validator/NullableClokeyIdExistValidator.java
  src/main/java/com/clokey/server/global/error/code/status/ErrorStatus.java
  src/main/java/com/clokey/server/global/error/code/status/SuccessStatus.java
Labels: :recycle: Refactor

#108 [feat/#106] 기록에 유저 토큰 적용
  src/main/java/com/clokey/server/domain/history/api/HistoryRestController.java
  src/main/java/com/clokey/server/domain/history/application/HistoryRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HistoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/converter/HistoryConverter.java
  src/main/java/com/clokey/server/domain/history/domain/repository/HistoryRepository.java
  src/main/java/com/clokey/server/domain/history/dto/HistoryResponseDTO.java
  src/main/java/com/clokey/server/domain/member/api/MemberRestController.java
  src/main/java/com/clokey/server/domain/member/application/FollowRepositoryService.java
  src/main/java/com/clokey/server/domain/member/application/FollowRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/member/domain/repository/FollowRepository.java
  src/main/java/com/clokey/server/domain/term/api/TermRestController.java
Labels: :sparkles: Feat

#110 [refactor/#109] DTO 수정
  src/main/java/com/clokey/server/domain/member/converter/GetUserConverter.java
  src/main/java/com/clokey/server/domain/member/converter/ProfileConverter.java
  src/main/java/com/clokey/server/domain/member/domain/entity/Member.java
  src/main/java/com/clokey/server/domain/member/dto/MemberDTO.java
Labels: :recycle: Refactor
