Repository Clokey-dev/Clokey_SpringBoot, pull requests merged in 2025-04, with the labels that each got.

#332 [fix/#331] 내 자신의 프로필을 조회할 경우 팔로워/팔로잉 목록 조회 가능하도록 수정
  src/main/java/com/clokey/server/domain/member/api/MemberRestController.java
  src/main/java/com/clokey/server/domain/member/application/MemberServiceImpl.java
Labels: :fire: Fix

#316 [refactor/#310] 스마트 요약 및 옷장 조회 API 리팩토링
  src/main/java/com/clokey/server/domain/cloth/api/ClothRestController.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothImageRepositoryService.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothImageRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothService.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothServiceImpl.java
  src/main/java/com/clokey/server/domain/cloth/converter/ClothConverter.java
  src/main/java/com/clokey/server/domain/cloth/domain/repository/ClothImageRepository.java
  src/main/java/com/clokey/server/domain/cloth/dto/ClothResponseDTO.java
  src/main/java/com/clokey/server/domain/history/application/HistoryRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/domain/repository/HistoryRepository.java
  src/main/java/com/clokey/server/domain/search/application/SearchRepositoryServiceImpl.java
Labels: :recycle: Refactor

#335 [refactor/#334] 옷장 조회 응답 형식 롤백
  src/main/java/com/clokey/server/domain/cloth/application/ClothServiceImpl.java
  src/main/java/com/clokey/server/domain/cloth/converter/ClothConverter.java
  src/main/java/com/clokey/server/domain/cloth/dto/ClothResponseDTO.java
Labels: :recycle: Refactor

#340 [fix/#339] 비공개 아이디는 표시되지 않도록 수정
  src/main/java/com/clokey/server/domain/member/application/FollowRepositoryServiceImpl.java
Labels: :fire: Fix

#342 [fix/#341] 비공개 아이디는 표시되도록 수정
  src/main/java/com/clokey/server/domain/member/application/FollowRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/member/application/MemberServiceImpl.java
Labels: :fire: Fix

#344 [fix/#343] ClokeyId를 통한 본인 조회시 정보 넘겨줌
  src/main/java/com/clokey/server/domain/member/application/MemberServiceImpl.java
Labels: :fire: Fix

#346 [feat/#345] 회원 즉시 탈퇴 API 구현
  src/main/java/com/clokey/server/domain/member/api/AuthController.java
  src/main/java/com/clokey/server/domain/member/application/UnlinkService.java
  src/main/java/com/clokey/server/domain/member/application/UnlinkServiceImpl.java
Labels: :sparkles: Feat

#348 [refactor/#347] hot 계정 로직 수정
  src/main/java/com/clokey/server/domain/history/domain/repository/HistoryRepository.java
  src/main/java/com/clokey/server/domain/member/application/FollowRepositoryService.java
  src/main/java/com/clokey/server/domain/member/application/FollowRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/member/domain/repository/FollowRepository.java
  src/main/java/com/clokey/server/domain/recommendation/application/RecommendationServiceImpl.java
Labels: :fire: Fix, :recycle: Refactor

#350 [refactor/#349] 내가 좋아요 한 기록 api 수정
  src/main/java/com/clokey/server/domain/history/api/HistoryRestController.java
  src/main/java/com/clokey/server/domain/history/application/HistoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/converter/HistoryConverter.java
  src/main/java/com/clokey/server/domain/history/dto/HistoryResponseDTO.java
Labels: :recycle: Refactor

#352 [refactor/#351] 배포 Github Action과 Docker 리펙토링
  .dockerignore
  .github/workflows/dev_deploy.yml
  Dockerfile
  deploy.sh
  docker-compose.yml
  gradle.properties
  settings.gradle
  src/main/java/com/clokey/server/domain/folder/api/FolderRestController.java
  src/main/java/com/clokey/server/domain/history/api/HistoryRestController.java
  src/main/java/com/clokey/server/domain/history/converter/HashtagSerializer.java
  src/main/java/com/clokey/server/domain/report/api/ReportRestController.java
  src/main/java/com/clokey/server/domain/term/application/MemberTermRepositoryServiceImpl.java
  src/main/java/com/clokey/server/global/common/response/BaseResponse.java
Labels: :recycle: Refactor
