Repository Clokey-dev/Clokey_SpringBoot, pull requests merged in 2025-03, with the labels that each got.

#286 [refactor/#285] history 기능 리펙토링 및 수정 사항 반영
  src/main/java/com/clokey/server/domain/history/application/HistoryRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/converter/HistoryConverter.java
  src/main/java/com/clokey/server/domain/history/domain/repository/HistoryRepository.java
  src/main/java/com/clokey/server/domain/member/api/MemberRestController.java
  src/main/java/com/clokey/server/domain/member/application/MemberService.java
  src/main/java/com/clokey/server/domain/member/application/MemberServiceImpl.java
  src/main/java/com/clokey/server/domain/member/converter/GetUserConverter.java
  src/main/java/com/clokey/server/domain/member/dto/MemberDTO.java
  src/main/java/com/clokey/server/domain/notification/application/NotificationServiceImpl.java
  src/main/java/com/clokey/server/domain/recommendation/application/RecommendationServiceImpl.java
  src/main/java/com/clokey/server/domain/recommendation/converter/RecommendationConverter.java
  src/main/java/com/clokey/server/domain/recommendation/dto/RecommendationResponseDTO.java
Labels: :fire: Fix, :recycle: Refactor

#292 [Feat/#288] 기록과 댓글을 신고하는 기능을 구현합니다.
  src/main/java/com/clokey/server/domain/model/entity/enums/CommentReportType.java
  src/main/java/com/clokey/server/domain/model/entity/enums/HistoryReportType.java
  src/main/java/com/clokey/server/domain/model/entity/enums/ReportStatus.java
  src/main/java/com/clokey/server/domain/report/api/ReportRestController.java
  src/main/java/com/clokey/server/domain/report/application/CommentReportRepositoryService.java
  src/main/java/com/clokey/server/domain/report/application/CommentReportRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/report/application/HistoryReportRepositoryService.java
  src/main/java/com/clokey/server/domain/report/application/HistoryReportRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/report/application/ReportService.java
  src/main/java/com/clokey/server/domain/report/application/ReportServiceImpl.java
  src/main/java/com/clokey/server/domain/report/converter/ReportConverter.java
  src/main/java/com/clokey/server/domain/report/domain/entity/CommentReport.java
  src/main/java/com/clokey/server/domain/report/domain/entity/HistoryReport.java
  src/main/java/com/clokey/server/domain/report/domain/repository/CommentReportRepository.java
  src/main/java/com/clokey/server/domain/report/domain/repository/HistoryReportRepository.java
  src/main/java/com/clokey/server/domain/report/dto/ReportRequestDTO.java
  src/main/java/com/clokey/server/domain/report/dto/ReportResponseDTO.java
  src/main/java/com/clokey/server/domain/report/exception/annotation/ReportLength.java
  src/main/java/com/clokey/server/domain/report/exception/validator/ReportLengthValidator.java
  src/main/java/com/clokey/server/global/error/code/status/ErrorStatus.java
  src/main/java/com/clokey/server/global/error/code/status/SuccessStatus.java
Labels: :sparkles: Feat

#301 [feat/#287] 계정차단/신고
  src/main/java/com/clokey/server/domain/member/api/MemberRestController.java
  src/main/java/com/clokey/server/domain/member/application/BlockRepositoryService.java
  src/main/java/com/clokey/server/domain/member/application/BlockRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/member/application/MemberService.java
  src/main/java/com/clokey/server/domain/member/application/MemberServiceImpl.java
  src/main/java/com/clokey/server/domain/member/converter/GetUserConverter.java
  src/main/java/com/clokey/server/domain/member/domain/entity/Block.java
  src/main/java/com/clokey/server/domain/member/domain/repository/BlockRepository.java
  src/main/java/com/clokey/server/domain/member/dto/MemberDTO.java
  src/main/java/com/clokey/server/domain/model/entity/enums/ProfileReportType.java
  src/main/java/com/clokey/server/domain/report/api/ReportRestController.java
  src/main/java/com/clokey/server/domain/report/application/ProfileReportRepositoryService.java
  src/main/java/com/clokey/server/domain/report/application/ProfileReportRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/report/application/ReportService.java
  src/main/java/com/clokey/server/domain/report/application/ReportServiceImpl.java
  src/main/java/com/clokey/server/domain/report/converter/ReportConverter.java
  src/main/java/com/clokey/server/domain/report/domain/entity/ProfileReport.java
  src/main/java/com/clokey/server/domain/report/domain/repository/ProfileReportRepository.java
  src/main/java/com/clokey/server/domain/report/dto/ReportRequestDTO.java
  src/main/java/com/clokey/server/domain/report/dto/ReportResponseDTO.java
  src/main/java/com/clokey/server/global/error/code/status/ErrorStatus.java
  src/main/java/com/clokey/server/global/error/code/status/SuccessStatus.java
Labels: :sparkles: Feat

#299 [refactor/#298] 해시태그 20개 제한
  src/main/java/com/clokey/server/domain/history/application/HistoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/dto/HistoryRequestDTO.java
  src/main/java/com/clokey/server/domain/history/exception/annotation/HashtagCondition.java
  src/main/java/com/clokey/server/domain/history/exception/validator/HashtagConditionValidator.java
  src/main/java/com/clokey/server/domain/notification/application/NotificationServiceImpl.java
  src/main/java/com/clokey/server/global/error/code/status/ErrorStatus.java
Labels: :fire: Fix, :recycle: Refactor

#295 [fix/#293] home api 수정
  src/main/java/com/clokey/server/domain/recommendation/application/RecommendationServiceImpl.java
Labels: :fire: Fix, :recycle: Refactor

#296 [feat/#294] 내가 좋아요 한 기록 API 구현
  src/main/java/com/clokey/server/domain/history/api/HistoryRestController.java
  src/main/java/com/clokey/server/domain/history/application/HistoryRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HistoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/converter/HistoryConverter.java
  src/main/java/com/clokey/server/domain/history/domain/repository/HistoryRepository.java
Labels: :sparkles: Feat

#304 [fix/#289] 엘라스틱 서치 관련 오류 수정 및 리팩토링
  src/main/java/com/clokey/server/domain/cloth/application/ClothService.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothServiceImpl.java
  src/main/java/com/clokey/server/domain/cloth/domain/document/ClothDocument.java
  src/main/java/com/clokey/server/domain/history/application/HistoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/domain/document/HistoryDocument.java
  src/main/java/com/clokey/server/domain/member/application/MemberService.java
  src/main/java/com/clokey/server/domain/member/application/MemberServiceImpl.java
  src/main/java/com/clokey/server/domain/member/application/UnlinkService.java
  src/main/java/com/clokey/server/domain/member/application/UnlinkServiceImpl.java
  src/main/java/com/clokey/server/domain/member/domain/document/MemberDocument.java
  src/main/java/com/clokey/server/domain/search/application/SearchRepositoryService.java
  src/main/java/com/clokey/server/domain/search/application/SearchRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/search/application/SearchServiceImpl.java
  src/main/java/com/clokey/server/domain/search/scheduler/ESFailedSyncCleanupTask.java
  src/main/resources/static/elastic-mapping-cloth.json
  src/main/resources/static/elastic-mapping-history.json
  src/main/resources/static/elastic-mapping-member.json
  src/main/resources/static/elastic-setting-cloth.json
  src/main/resources/static/elastic-setting-history.json
  src/main/resources/static/elastic-setting-member.json
Labels: :fire: Fix, :recycle: Refactor

#303 [refactor/#302] block refactor
  src/main/java/com/clokey/server/domain/member/application/MemberServiceImpl.java
  src/main/java/com/clokey/server/domain/member/converter/GetUserConverter.java
  src/main/java/com/clokey/server/domain/member/dto/MemberDTO.java
Labels: :recycle: Refactor

#306 [feat/#300] 관리자용 신고 조회 API
  build.gradle
  src/main/java/com/clokey/server/domain/history/exception/validator/HashtagConditionValidator.java
  src/main/java/com/clokey/server/domain/model/entity/enums/ReportType.java
  src/main/java/com/clokey/server/domain/report/api/ReportRestController.java
  src/main/java/com/clokey/server/domain/report/application/CommentReportRepositoryService.java
  src/main/java/com/clokey/server/domain/report/application/CommentReportRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/report/application/HistoryReportRepositoryService.java
  src/main/java/com/clokey/server/domain/report/application/HistoryReportRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/report/application/ProfileReportRepositoryService.java
  src/main/java/com/clokey/server/domain/report/application/ProfileReportRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/report/application/ReportService.java
  src/main/java/com/clokey/server/domain/report/application/ReportServiceImpl.java
  src/main/java/com/clokey/server/domain/report/converter/ReportConverter.java
  src/main/java/com/clokey/server/domain/report/domain/repository/CommentReportRepository.java
  src/main/java/com/clokey/server/domain/report/domain/repository/HistoryReportRepository.java
  src/main/java/com/clokey/server/domain/report/domain/repository/ProfileReportRepository.java
  src/main/java/com/clokey/server/domain/report/dto/ReportResponseDTO.java
  src/main/java/com/clokey/server/domain/report/exception/ReportException.java
  src/main/java/com/clokey/server/global/error/code/status/ErrorStatus.java
  src/main/java/com/clokey/server/global/error/code/status/SuccessStatus.java
Labels: :sparkles: Feat, :recycle: Refactor

#305 [feat/#291] 검색시 차단한 유저 제외 로직 추가
  src/main/java/com/clokey/server/domain/history/domain/document/HistoryDocument.java
  src/main/java/com/clokey/server/domain/search/api/SearchRestController.java
  src/main/java/com/clokey/server/domain/search/application/SearchRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/search/application/SearchService.java
  src/main/java/com/clokey/server/domain/search/application/SearchServiceImpl.java
Labels: :sparkles: Feat

#308 [feat/#297] 내가 남긴 댓글 조회 API 구현
  src/main/java/com/clokey/server/domain/history/api/HistoryRestController.java
  src/main/java/com/clokey/server/domain/history/application/CommentRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/CommentRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HistoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/converter/HistoryConverter.java
  src/main/java/com/clokey/server/domain/history/domain/repository/CommentRepository.java
  src/main/java/com/clokey/server/domain/history/dto/HistoryResponseDTO.java
Labels: :sparkles: Feat

#313 [refactor/#312] 내가 남긴 댓글 api nickname 수정
  src/main/java/com/clokey/server/domain/history/converter/HistoryConverter.java
  src/main/java/com/clokey/server/domain/history/dto/HistoryResponseDTO.java
Labels: :recycle: Refactor

#315 [refactor/#314] 내가 남긴 댓글 api historyId 추가
  src/main/java/com/clokey/server/domain/history/converter/HistoryConverter.java
  src/main/java/com/clokey/server/domain/history/dto/HistoryResponseDTO.java
Labels: :recycle: Refactor

#318 [fix/#317] isMine null 처리
  src/main/java/com/clokey/server/domain/recommendation/application/RecommendationServiceImpl.java
Labels: :fire: Fix

#319 [feat/#307] 신고 처리 프로레스 구현
  src/main/java/com/clokey/server/domain/history/application/CommentRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/CommentRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HistoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/domain/entity/Comment.java
  src/main/java/com/clokey/server/domain/history/domain/entity/History.java
  src/main/java/com/clokey/server/domain/history/domain/repository/CommentRepository.java
  src/main/java/com/clokey/server/domain/member/application/MemberServiceImpl.java
  src/main/java/com/clokey/server/domain/member/domain/entity/Member.java
  src/main/java/com/clokey/server/domain/member/dto/MemberDTO.java
  src/main/java/com/clokey/server/domain/report/api/ReportRestController.java
  src/main/java/com/clokey/server/domain/report/application/CommentReportRepositoryService.java
  src/main/java/com/clokey/server/domain/report/application/CommentReportRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/report/application/HistoryReportRepositoryService.java
  src/main/java/com/clokey/server/domain/report/application/HistoryReportRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/report/application/ProfileReportRepositoryService.java
  src/main/java/com/clokey/server/domain/report/application/ProfileReportRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/report/application/ReportService.java
  src/main/java/com/clokey/server/domain/report/application/ReportServiceImpl.java
  src/main/java/com/clokey/server/domain/report/domain/entity/CommentReport.java
  src/main/java/com/clokey/server/domain/report/domain/entity/HistoryReport.java
  src/main/java/com/clokey/server/domain/report/domain/entity/ProfileReport.java
  src/main/java/com/clokey/server/global/error/code/status/ErrorStatus.java
  src/main/java/com/clokey/server/global/error/code/status/SuccessStatus.java
Labels: :sparkles: Feat

#320 [feat/#309] 차단회원 홈 소식에 적용
  src/main/java/com/clokey/server/domain/cloth/application/ClothRepositoryService.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/cloth/domain/repository/ClothRepository.java
  src/main/java/com/clokey/server/domain/history/application/HashtagHistoryRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HashtagHistoryRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HistoryClothRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryClothRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/domain/repository/HashtagHistoryRepository.java
  src/main/java/com/clokey/server/domain/history/domain/repository/HistoryClothRepository.java
  src/main/java/com/clokey/server/domain/recommendation/application/RecommendationServiceImpl.java
  src/main/java/com/clokey/server/domain/recommendation/converter/RecommendationConverter.java
  src/main/java/com/clokey/server/domain/recommendation/dto/RecommendationResponseDTO.java
Labels: :sparkles: Feat, :recycle: Refactor

#323 [feat/#322] JWT 토큰 이메일 식별자에서 Long id값으로 수정
  src/main/java/com/clokey/server/domain/member/application/AuthService.java
  src/main/java/com/clokey/server/domain/member/application/AuthServiceImpl.java
  src/main/java/com/clokey/server/global/config/security/auth/PrincipalDetailsService.java
  src/main/java/com/clokey/server/global/config/security/jwt/JwtRequestFilter.java
Labels: :recycle: Refactor

#327 Feat/#324 isMe 추가
  src/main/java/com/clokey/server/domain/member/application/MemberServiceImpl.java
  src/main/java/com/clokey/server/domain/member/converter/GetUserConverter.java
  src/main/java/com/clokey/server/domain/member/dto/MemberDTO.java
Labels: :sparkles: Feat

#328 [refactor/#321] 좋아요 한 기록 갯수 수정
  src/main/java/com/clokey/server/domain/history/application/HistoryServiceImpl.java
Labels: :recycle: Refactor

#330 [refactor/#329] 약관동의 로직수정
  src/main/java/com/clokey/server/domain/term/application/MemberTermRepositoryService.java
  src/main/java/com/clokey/server/domain/term/application/MemberTermRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/term/application/TermCommandServiceImpl.java
  src/main/java/com/clokey/server/domain/term/domain/repository/MemberTermRepository.java
  src/main/java/com/clokey/server/domain/term/exception/validator/EssentialTermAgreeValidator.java
Labels: :recycle: Refactor
