Repository Clokey-dev/Clokey_SpringBoot, pull requests merged in 2025-02, with the labels that each got.

#112 [feat/#65] 옷장 조회 API 구현
  src/main/java/com/clokey/server/domain/category/exception/validator/CategoryExistValidator.java
  src/main/java/com/clokey/server/domain/cloth/api/ClothRestController.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothRepositoryService.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothService.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothServiceImpl.java
  src/main/java/com/clokey/server/domain/cloth/converter/ClothConverter.java
  src/main/java/com/clokey/server/domain/cloth/domain/repository/ClothRepository.java
  src/main/java/com/clokey/server/domain/cloth/dto/ClothRequestDTO.java
  src/main/java/com/clokey/server/domain/cloth/dto/ClothResponseDTO.java
  src/main/java/com/clokey/server/domain/model/entity/enums/ClothSort.java
  src/main/java/com/clokey/server/domain/model/entity/enums/Season.java
  src/main/java/com/clokey/server/global/config/EnumConverterConfig.java
  src/main/java/com/clokey/server/global/converter/StringToEnumConverter.java
Labels: :sparkles: Feat

#113 [feat/#111] token api
  src/main/java/com/clokey/server/domain/member/api/AuthController.java
  src/main/java/com/clokey/server/domain/member/api/MemberRestController.java
  src/main/java/com/clokey/server/domain/member/application/AuthService.java
  src/main/java/com/clokey/server/domain/member/application/AuthServiceImpl.java
  src/main/java/com/clokey/server/domain/member/application/GetUserQueryService.java
  src/main/java/com/clokey/server/domain/member/application/GetUserQueryServiceImpl.java
  src/main/java/com/clokey/server/domain/member/converter/GetUserConverter.java
  src/main/java/com/clokey/server/domain/member/dto/AuthDTO.java
  src/main/java/com/clokey/server/domain/member/dto/MemberDTO.java
  src/main/java/com/clokey/server/domain/term/api/TermRestController.java
  src/main/java/com/clokey/server/domain/term/application/TermCommandService.java
  src/main/java/com/clokey/server/domain/term/application/TermCommandServiceImpl.java
  src/main/java/com/clokey/server/domain/term/converter/TermConverter.java
  src/main/java/com/clokey/server/domain/term/dto/TermResponseDTO.java
  src/main/java/com/clokey/server/global/error/code/status/ErrorStatus.java
  src/main/java/com/clokey/server/global/error/code/status/SuccessStatus.java
Labels: :sparkles: Feat

#117 [feat/#114] 옷 API에 토큰 추출 적용 및 validator 수정
  src/main/java/com/clokey/server/domain/cloth/api/ClothRestController.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothRepositoryService.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothService.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothServiceImpl.java
  src/main/java/com/clokey/server/domain/cloth/domain/repository/ClothRepository.java
  src/main/java/com/clokey/server/domain/cloth/dto/ClothRequestDTO.java
  src/main/java/com/clokey/server/domain/cloth/exception/validator/ClothAccessibleValidator.java
  src/main/java/com/clokey/server/domain/member/exception/validator/MemberAccessibleValidator.java
  src/main/java/com/clokey/server/global/error/code/status/ErrorStatus.java
  src/main/java/com/clokey/server/global/error/exception/annotation/CheckPageSize.java
  src/main/java/com/clokey/server/global/error/exception/validator/CheckPageSizeValidator.java
Labels: :sparkles: Feat

#122 [feat/#121] 폴더에 있는 옷 삭제 api 구현 및 리팩토링
  src/main/java/com/clokey/server/domain/folder/api/FolderRestController.java
  src/main/java/com/clokey/server/domain/folder/application/ClothFolderRepositoryService.java
  src/main/java/com/clokey/server/domain/folder/application/ClothFolderRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/folder/application/FolderService.java
  src/main/java/com/clokey/server/domain/folder/application/FolderServiceImpl.java
  src/main/java/com/clokey/server/domain/folder/domain/repository/ClothFolderRepository.java
  src/main/java/com/clokey/server/domain/folder/dto/FolderRequestDTO.java
  src/main/java/com/clokey/server/domain/folder/exception/validator/FolderAccessibleValidator.java
  src/main/java/com/clokey/server/global/error/code/status/SuccessStatus.java
Labels: :sparkles: Feat, :recycle: Refactor

#124 [refactor/#123] 댓글 반환시에 닉네임을 반환하도록 수정
  src/main/java/com/clokey/server/domain/history/converter/HistoryConverter.java
  src/main/java/com/clokey/server/domain/history/dto/HistoryResponseDTO.java
Labels: :recycle: Refactor

#127 [feat/#125] elastiCache로 redis 구현 완료
  build.gradle
  src/main/java/com/clokey/server/ServerApplication.java
  src/main/java/com/clokey/server/domain/RedisService.java
  src/main/java/com/clokey/server/global/config/RedisConfig.java
  src/test/java/com/clokey/server/domain/RedisServiceTest.java
Labels: :sparkles: Feat

#130 [refactor/#129] 폴더 생성 api 로직 수정
  src/main/java/com/clokey/server/domain/folder/application/FolderServiceImpl.java
  src/main/java/com/clokey/server/domain/folder/dto/FolderRequestDTO.java
Labels: :recycle: Refactor

#140 [fix/#138] history가 기록될 경우 wearnum이 올라가지 않던 오류 해결
  src/main/java/com/clokey/server/domain/history/application/HistoryClothRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HistoryServiceImpl.java
Labels: :fire: Fix

#141 [feat/#126] apple login
  build.gradle
  src/main/java/com/clokey/server/domain/member/api/AuthController.java
  src/main/java/com/clokey/server/domain/member/application/AppleAuthService.java
  src/main/java/com/clokey/server/domain/member/application/AppleAuthServiceImpl.java
  src/main/java/com/clokey/server/domain/member/application/GetUserQueryServiceImpl.java
  src/main/java/com/clokey/server/domain/member/converter/GetUserConverter.java
  src/main/java/com/clokey/server/domain/member/dto/AuthDTO.java
  src/main/java/com/clokey/server/domain/member/dto/MemberDTO.java
  src/main/java/com/clokey/server/global/error/code/status/ErrorStatus.java
Labels: :sparkles: Feat

#144 [feat/#126] apple login
  src/main/java/com/clokey/server/domain/member/application/AppleAuthServiceImpl.java
  src/main/java/com/clokey/server/global/error/code/status/ErrorStatus.java
Labels: :fire: Fix

#142 [feat/#133] 사용자의 모든 폴더 조회 api 구현
  src/main/java/com/clokey/server/domain/folder/api/FolderRestController.java
  src/main/java/com/clokey/server/domain/folder/application/ClothFolderRepositoryService.java
  src/main/java/com/clokey/server/domain/folder/application/ClothFolderRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/folder/application/FolderRepositoryService.java
  src/main/java/com/clokey/server/domain/folder/application/FolderRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/folder/application/FolderService.java
  src/main/java/com/clokey/server/domain/folder/application/FolderServiceImpl.java
  src/main/java/com/clokey/server/domain/folder/converter/FolderConverter.java
  src/main/java/com/clokey/server/domain/folder/domain/entity/Folder.java
  src/main/java/com/clokey/server/domain/folder/domain/repository/ClothFolderRepository.java
  src/main/java/com/clokey/server/domain/folder/domain/repository/FolderRepository.java
  src/main/java/com/clokey/server/domain/folder/dto/FolderResponseDTO.java
Labels: :sparkles: Feat, :recycle: Refactor

#148 [fix/#147] 옷의 사진을 던지도록 수정
  src/main/java/com/clokey/server/domain/history/converter/HistoryConverter.java
Labels: :fire: Fix

#146 [fix/#126] 애플로그인 구현 성공
  src/main/java/com/clokey/server/domain/member/api/AuthController.java
  src/main/java/com/clokey/server/domain/member/api/MemberRestController.java
  src/main/java/com/clokey/server/domain/member/application/AppleAuthServiceImpl.java
Labels: :fire: Fix

#153 [fix/#154] 기록 좋아요 버그 수정
  src/main/java/com/clokey/server/domain/history/application/HistoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/domain/repository/HistoryRepository.java
  src/main/java/com/clokey/server/domain/history/dto/HistoryRequestDTO.java
  src/main/java/com/clokey/server/domain/history/exception/validator/HistoryLikedValidator.java
Labels: :fire: Fix

#155 [refactor/#154] 기록 일별 조회 API 수정
  src/main/java/com/clokey/server/domain/history/converter/HistoryConverter.java
  src/main/java/com/clokey/server/domain/history/dto/HistoryResponseDTO.java
Labels: :recycle: Refactor

#157 [fix/#156] 기록 좋아요 api, 기록 조회 api 수정
  src/main/java/com/clokey/server/domain/history/application/CommentRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/CommentRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HistoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/converter/HistoryConverter.java
  src/main/java/com/clokey/server/domain/history/domain/repository/CommentRepository.java
  src/main/java/com/clokey/server/domain/history/domain/repository/HistoryRepository.java
  src/main/java/com/clokey/server/domain/history/dto/HistoryResponseDTO.java
Labels: :fire: Fix, :recycle: Refactor

#139 [feat/#118] 스마트 요약 API 구현
  src/main/java/com/clokey/server/domain/category/exception/CategoryException.java
  src/main/java/com/clokey/server/domain/cloth/api/ClothRestController.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothRepositoryService.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothService.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothServiceImpl.java
  src/main/java/com/clokey/server/domain/cloth/converter/ClothConverter.java
  src/main/java/com/clokey/server/domain/cloth/domain/repository/ClothRepository.java
  src/main/java/com/clokey/server/domain/cloth/dto/ClothResponseDTO.java
  src/main/java/com/clokey/server/domain/history/application/HistoryRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/domain/repository/HistoryRepository.java
  src/main/java/com/clokey/server/global/error/code/status/ErrorStatus.java
Labels: :sparkles: Feat

#158 [feat/#143] 카테고리 추천 API 구현
  src/main/java/com/clokey/server/domain/category/api/CategoryRestController.java
  src/main/java/com/clokey/server/domain/category/application/CategoryService.java
  src/main/java/com/clokey/server/domain/category/application/CategoryServiceImpl.java
  src/main/java/com/clokey/server/domain/category/converter/CategoryConverter.java
  src/main/java/com/clokey/server/domain/category/dto/CategoryResponseDTO.java
Labels: :sparkles: Feat

#163 [refactor/#162] 로그인 필드 수정
  src/main/java/com/clokey/server/domain/member/dto/AuthDTO.java
Labels: :recycle: Refactor

#167 [refactor/#160] 스마트 요약 API 리팩토링
  src/main/java/com/clokey/server/domain/cloth/api/ClothRestController.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothService.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothServiceImpl.java
  src/main/java/com/clokey/server/domain/cloth/converter/ClothConverter.java
  src/main/java/com/clokey/server/domain/cloth/dto/ClothResponseDTO.java
Labels: :recycle: Refactor

#168 [refactor/#166] 옷장 조회 API 리팩토링
  src/main/java/com/clokey/server/domain/cloth/api/ClothRestController.java
  src/main/java/com/clokey/server/domain/member/exception/annotation/ClokeyIdExist.java
  src/main/java/com/clokey/server/domain/member/exception/validator/ClokeyIdExistValidator.java
Labels: :recycle: Refactor

#170 [feat/#150] 알림 구현 완료
  .github/workflows/dev_deploy.yml
  build.gradle
  src/main/java/com/clokey/server/domain/history/api/HistoryRestController.java
  src/main/java/com/clokey/server/domain/history/application/CommentRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/CommentRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/domain/repository/CommentRepository.java
  src/main/java/com/clokey/server/domain/history/exception/annotation/CommentExist.java
  src/main/java/com/clokey/server/domain/history/exception/validator/CommentExistValidator.java
  src/main/java/com/clokey/server/domain/member/application/FollowRepositoryService.java
  src/main/java/com/clokey/server/domain/member/application/FollowRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/member/domain/entity/Member.java
  src/main/java/com/clokey/server/domain/member/domain/repository/FollowRepository.java
  src/main/java/com/clokey/server/domain/model/entity/enums/NotificationType.java
  src/main/java/com/clokey/server/domain/model/entity/enums/RedirectType.java
  src/main/java/com/clokey/server/domain/notification/api/NotificationRestController.java
  src/main/java/com/clokey/server/domain/notification/application/NotificationRepositoryService.java
  src/main/java/com/clokey/server/domain/notification/application/NotificationRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/notification/application/NotificationService.java
  src/main/java/com/clokey/server/domain/notification/application/NotificationServiceImpl.java
  src/main/java/com/clokey/server/domain/notification/domain/entity/ClokeyNotification.java
  src/main/java/com/clokey/server/domain/notification/domain/repository/NotificationRepository.java
  src/main/java/com/clokey/server/domain/notification/dto/NotificationResponseDTO.java
  src/main/java/com/clokey/server/domain/notification/exception/NotificationException.java
  src/main/java/com/clokey/server/domain/notification/exception/annotation/NotificationExist.java
  src/main/java/com/clokey/server/domain/notification/exception/validator/NotificationExistValidator.java
  src/main/java/com/clokey/server/global/config/FCMConfig.java
  src/main/java/com/clokey/server/global/config/FirebaseProperties.java
  src/main/java/com/clokey/server/global/error/code/status/ErrorStatus.java
  src/main/java/com/clokey/server/global/error/code/status/SuccessStatus.java
Labels: :sparkles: Feat

#171 [feat/#161] 홈 - 소식 api 구현 (전체보기, 상세보기)
  src/main/java/com/clokey/server/domain/category/application/CategoryServiceImpl.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothRepositoryService.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/cloth/domain/repository/ClothRepository.java
  src/main/java/com/clokey/server/domain/folder/api/FolderRestController.java
  src/main/java/com/clokey/server/domain/history/api/HistoryRestController.java
  src/main/java/com/clokey/server/domain/history/application/HashtagHistoryRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HashtagHistoryRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HashtagRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HashtagRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HistoryImageRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryImageRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HistoryRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HistoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/converter/HistoryConverter.java
  src/main/java/com/clokey/server/domain/history/domain/repository/HashtagHistoryRepository.java
  src/main/java/com/clokey/server/domain/history/domain/repository/HashtagRepository.java
  src/main/java/com/clokey/server/domain/history/domain/repository/HistoryImageRepository.java
  src/main/java/com/clokey/server/domain/history/domain/repository/HistoryRepository.java
  src/main/java/com/clokey/server/domain/member/api/MemberRestController.java
  src/main/java/com/clokey/server/domain/member/application/MemberRepositoryService.java
  src/main/java/com/clokey/server/domain/model/entity/enums/NewsType.java
  src/main/java/com/clokey/server/domain/recommendation/api/RecommendationController.java
  src/main/java/com/clokey/server/domain/recommendation/application/RecommendationRepositoryService.java
  src/main/java/com/clokey/server/domain/recommendation/application/RecommendationRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/recommendation/application/RecommendationService.java
  src/main/java/com/clokey/server/domain/recommendation/application/RecommendationServiceImpl.java
  src/main/java/com/clokey/server/domain/recommendation/converter/RecommendationConverter.java
  src/main/java/com/clokey/server/domain/recommendation/domain/entity/Recommendation.java
  src/main/java/com/clokey/server/domain/recommendation/domain/repository/RecommendationRepository.java
  src/main/java/com/clokey/server/domain/recommendation/dto/RecommendationResponseDTO.java
  src/main/java/com/clokey/server/domain/recommendation/exception/annotation/CheckSection.java
  src/main/java/com/clokey/server/domain/recommendation/exception/validator/CheckSectionValidator.java
  src/main/java/com/clokey/server/global/config/RedisConfig.java
  src/main/java/com/clokey/server/global/error/code/status/ErrorStatus.java
Labels: :sparkles: Feat

#178 [refactor/#177] 로그인 dto deviceToken 추가
  src/main/java/com/clokey/server/domain/member/api/AuthController.java
  src/main/java/com/clokey/server/domain/member/application/AppleAuthService.java
  src/main/java/com/clokey/server/domain/member/application/AppleAuthServiceImpl.java
  src/main/java/com/clokey/server/domain/member/domain/entity/Member.java
  src/main/java/com/clokey/server/domain/member/dto/AuthDTO.java
Labels: :recycle: Refactor

#182 [feat/#159] 엘라스틱 서치 적용 및 옷장 내에서 검색 API 일부 구현
  build.gradle
  src/main/java/com/clokey/server/domain/cloth/api/ClothRestController.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothRepositoryService.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothService.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothServiceImpl.java
  src/main/java/com/clokey/server/domain/cloth/converter/ClothConverter.java
  src/main/java/com/clokey/server/domain/cloth/domain/document/ClothDocument.java
  src/main/java/com/clokey/server/domain/cloth/domain/entity/Cloth.java
  src/main/java/com/clokey/server/domain/cloth/domain/repository/ClothRepository.java
  src/main/java/com/clokey/server/domain/cloth/dto/ClothResponseDTO.java
  src/main/java/com/clokey/server/domain/history/domain/document/HistoryDocument.java
  src/main/java/com/clokey/server/domain/member/domain/document/MemberDocument.java
  src/main/java/com/clokey/server/domain/search/api/SearchRestController.java
  src/main/java/com/clokey/server/domain/search/application/SearchService.java
  src/main/java/com/clokey/server/domain/search/application/SearchServiceImpl.java
  src/main/java/com/clokey/server/domain/search/exception/SearchException.java
  src/main/java/com/clokey/server/global/config/ElasticsearchConfig.java
  src/main/java/com/clokey/server/global/error/code/status/ErrorStatus.java
  src/main/java/com/clokey/server/global/error/code/status/SuccessStatus.java
Labels: :sparkles: Feat

#187 [fix/#186] 도커 컴포즈 수정
  docker-compose.yml
Labels: :fire: Fix

#179 [feat/107] 오늘 날씨에 맞는 옷 추천 구현
  src/main/java/com/clokey/server/domain/cloth/application/ClothRepositoryService.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/cloth/domain/repository/ClothRepository.java
  src/main/java/com/clokey/server/domain/history/dto/HistoryResponseDTO.java
  src/main/java/com/clokey/server/domain/recommendation/api/RecommendationController.java
  src/main/java/com/clokey/server/domain/recommendation/application/RecommendationService.java
  src/main/java/com/clokey/server/domain/recommendation/application/RecommendationServiceImpl.java
  src/main/java/com/clokey/server/domain/recommendation/converter/RecommendationConverter.java
  src/main/java/com/clokey/server/domain/recommendation/exception/RecommendException.java
  src/main/java/com/clokey/server/domain/recommendation/exception/annotation/CheckTemperature.java
  src/main/java/com/clokey/server/domain/recommendation/exception/validator/CheckTemperatureValidator.java
  src/main/java/com/clokey/server/global/error/code/status/ErrorStatus.java
Labels: :sparkles: Feat

#191 [refactor/#190] DockerFile 로컬 시간 반영
  Dockerfile
Labels: :recycle: Refactor

#192 [refactor/#169] 옷 관련 API 리팩토링
  src/main/java/com/clokey/server/domain/cloth/converter/ClothConverter.java
  src/main/java/com/clokey/server/domain/cloth/dto/ClothResponseDTO.java
  src/main/java/com/clokey/server/domain/member/exception/annotation/ClokeyIdExist.java
  src/main/java/com/clokey/server/domain/member/exception/validator/ClokeyIdExistValidator.java
Labels: :recycle: Refactor

#195 [feat/#176] 선택약관 조회변경
  src/main/java/com/clokey/server/domain/member/api/MemberRestController.java
  src/main/java/com/clokey/server/domain/member/application/GetUserQueryServiceImpl.java
  src/main/java/com/clokey/server/domain/member/converter/GetUserConverter.java
  src/main/java/com/clokey/server/domain/member/dto/AuthDTO.java
  src/main/java/com/clokey/server/domain/member/dto/MemberDTO.java
  src/main/java/com/clokey/server/domain/term/api/TermRestController.java
  src/main/java/com/clokey/server/domain/term/application/MemberTermRepositoryService.java
  src/main/java/com/clokey/server/domain/term/application/MemberTermRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/term/application/TermCommandService.java
  src/main/java/com/clokey/server/domain/term/application/TermCommandServiceImpl.java
  src/main/java/com/clokey/server/domain/term/application/TermRepositoryService.java
  src/main/java/com/clokey/server/domain/term/application/TermRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/term/domain/repository/MemberTermRepository.java
  src/main/java/com/clokey/server/domain/term/domain/repository/TermRepository.java
  src/main/java/com/clokey/server/domain/term/dto/TermRequestDTO.java
  src/main/java/com/clokey/server/domain/term/dto/TermResponseDTO.java
  src/main/java/com/clokey/server/domain/term/exception/annotation/InvalidTermId.java
  src/main/java/com/clokey/server/domain/term/exception/validator/InvalidTermIdValidator.java
  src/main/java/com/clokey/server/global/error/code/status/ErrorStatus.java
  src/main/java/com/clokey/server/global/error/code/status/SuccessStatus.java
Labels: :sparkles: Feat

#197 [feat/#183] 계정 검색 API 구현
  src/main/java/com/clokey/server/domain/member/application/MemberRepositoryService.java
  src/main/java/com/clokey/server/domain/member/application/MemberRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/member/converter/MemberDocumentConverter.java
  src/main/java/com/clokey/server/domain/member/domain/repository/MemberRepository.java
  src/main/java/com/clokey/server/domain/member/dto/MemberDTO.java
  src/main/java/com/clokey/server/domain/search/api/SearchRestController.java
  src/main/java/com/clokey/server/domain/search/application/SearchService.java
  src/main/java/com/clokey/server/domain/search/application/SearchServiceImpl.java
Labels: :sparkles: Feat

#199 [refactor/#198] 소셜타입 추가 제공
  src/main/java/com/clokey/server/domain/term/application/TermCommandServiceImpl.java
  src/main/java/com/clokey/server/domain/term/dto/TermResponseDTO.java
Labels: :recycle: Refactor

#200 [feat/#184] 기록 검색 API 구현
  src/main/java/com/clokey/server/domain/history/application/HistoryRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/converter/HistoryConverter.java
  src/main/java/com/clokey/server/domain/history/domain/document/HistoryDocument.java
  src/main/java/com/clokey/server/domain/history/domain/repository/HistoryRepository.java
  src/main/java/com/clokey/server/domain/history/dto/HistoryResponseDTO.java
  src/main/java/com/clokey/server/domain/search/api/SearchRestController.java
  src/main/java/com/clokey/server/domain/search/application/SearchService.java
  src/main/java/com/clokey/server/domain/search/application/SearchServiceImpl.java
Labels: :sparkles: Feat

#193 [refactor/#180] 폴더 생성 및 수정 api로 수정
  src/main/java/com/clokey/server/domain/folder/api/FolderRestController.java
  src/main/java/com/clokey/server/domain/folder/application/ClothFolderRepositoryService.java
  src/main/java/com/clokey/server/domain/folder/application/ClothFolderRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/folder/application/FolderService.java
  src/main/java/com/clokey/server/domain/folder/application/FolderServiceImpl.java
  src/main/java/com/clokey/server/domain/folder/domain/entity/Folder.java
  src/main/java/com/clokey/server/domain/folder/domain/repository/ClothFolderRepository.java
  src/main/java/com/clokey/server/domain/folder/dto/FolderRequestDTO.java
  src/main/java/com/clokey/server/global/error/code/status/SuccessStatus.java
Labels: :sparkles: Feat, :recycle: Refactor

#203 [fix/#202] 일별 기록 조회 옷의 공개 범위 고려
  src/main/java/com/clokey/server/domain/history/application/HistoryServiceImpl.java
Labels: :fire: Fix

#208 [fix/#184] 옷장 검색 시에ClokeyId 입력받는 로직 추가
  src/main/java/com/clokey/server/domain/cloth/domain/document/ClothDocument.java
  src/main/java/com/clokey/server/domain/search/api/SearchRestController.java
  src/main/java/com/clokey/server/domain/search/application/SearchService.java
  src/main/java/com/clokey/server/domain/search/application/SearchServiceImpl.java
Labels: :fire: Fix

#206 [feat/#194] 알림 조회 api 구현
  src/main/java/com/clokey/server/domain/notification/api/NotificationRestController.java
  src/main/java/com/clokey/server/domain/notification/application/NotificationRepositoryService.java
  src/main/java/com/clokey/server/domain/notification/application/NotificationRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/notification/application/NotificationService.java
  src/main/java/com/clokey/server/domain/notification/application/NotificationServiceImpl.java
  src/main/java/com/clokey/server/domain/notification/converter/NotificationConverter.java
  src/main/java/com/clokey/server/domain/notification/domain/repository/NotificationRepository.java
  src/main/java/com/clokey/server/domain/notification/dto/NotificationResponseDTO.java
Labels: :sparkles: Feat

#211 [fix/#204] 기록 사진이 없는 경우 옷의 사진을 던지도록 수정
  src/main/java/com/clokey/server/domain/history/api/HistoryRestController.java
  src/main/java/com/clokey/server/domain/history/application/HistoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/exception/validator/UniqueClothesValidator.java
  src/main/java/com/clokey/server/global/error/code/status/ErrorStatus.java
Labels: :fire: Fix

#213 [feat/#185] JPA 엔티티와 ES 동기화 로직 구현
  src/main/java/com/clokey/server/domain/cloth/application/ClothServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HistoryServiceImpl.java
  src/main/java/com/clokey/server/domain/member/application/AppleAuthServiceImpl.java
  src/main/java/com/clokey/server/domain/member/application/AuthServiceImpl.java
  src/main/java/com/clokey/server/domain/member/application/ProfileCommandServiceImpl.java
  src/main/java/com/clokey/server/domain/search/api/SearchRestController.java
  src/main/java/com/clokey/server/domain/search/application/SearchRepositoryService.java
  src/main/java/com/clokey/server/domain/search/application/SearchRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/search/application/SearchService.java
  src/main/java/com/clokey/server/domain/search/application/SearchServiceImpl.java
  src/main/java/com/clokey/server/domain/search/exception/validator/KeywordNotNullValidator.java
  src/main/java/com/clokey/server/global/error/code/status/ErrorStatus.java
Labels: :sparkles: Feat, :recycle: Refactor

#215 [refactor/#210] nori 플러그인 적용
  src/main/java/com/clokey/server/domain/cloth/domain/document/ClothDocument.java
  src/main/java/com/clokey/server/domain/history/domain/document/HistoryDocument.java
  src/main/java/com/clokey/server/domain/member/domain/document/MemberDocument.java
  src/main/resources/static/elastic-mapping.json
  src/main/resources/static/elastic-setting.json
Labels: :sparkles: Feat

#214 [refactor/#209] Redis 캐시 로직 수정
  src/main/java/com/clokey/server/domain/history/application/HashtagHistoryRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HashtagHistoryRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/domain/repository/HashtagHistoryRepository.java
  src/main/java/com/clokey/server/domain/recommendation/application/RecommendationServiceImpl.java
  src/main/java/com/clokey/server/domain/recommendation/converter/RecommendationConverter.java
  src/main/java/com/clokey/server/domain/recommendation/dto/RecommendationResponseDTO.java
  src/main/java/com/clokey/server/global/infra/redis/RedisService.java
  src/test/java/com/clokey/server/domain/RedisServiceTest.java
Labels: :sparkles: Feat, :recycle: Refactor

#219 [refactor/#218] home DTO에서 datetime -> date로 수정
  src/main/java/com/clokey/server/domain/recommendation/converter/RecommendationConverter.java
  src/main/java/com/clokey/server/domain/recommendation/dto/RecommendationResponseDTO.java
Labels: :recycle: Refactor

#175 [feat/#151] logout unlink
  src/main/java/com/clokey/server/ServerApplication.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothImageRepositoryService.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothImageRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothRepositoryService.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/cloth/domain/repository/ClothImageRepository.java
  src/main/java/com/clokey/server/domain/cloth/domain/repository/ClothRepository.java
  src/main/java/com/clokey/server/domain/folder/application/ClothFolderRepositoryService.java
  src/main/java/com/clokey/server/domain/folder/application/ClothFolderRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/folder/application/FolderRepositoryService.java
  src/main/java/com/clokey/server/domain/folder/application/FolderRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/folder/domain/repository/ClothFolderRepository.java
  src/main/java/com/clokey/server/domain/folder/domain/repository/FolderRepository.java
  src/main/java/com/clokey/server/domain/history/application/CommentRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/CommentRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HashtagHistoryRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HashtagHistoryRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HistoryClothRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryClothRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HistoryImageRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryImageRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HistoryRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/MemberLikeRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/MemberLikeRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/domain/repository/CommentRepository.java
  src/main/java/com/clokey/server/domain/history/domain/repository/HashtagHistoryRepository.java
  src/main/java/com/clokey/server/domain/history/domain/repository/HistoryClothRepository.java
  src/main/java/com/clokey/server/domain/history/domain/repository/HistoryImageRepository.java
  src/main/java/com/clokey/server/domain/history/domain/repository/HistoryRepository.java
  src/main/java/com/clokey/server/domain/history/domain/repository/MemberLikeRepository.java
  src/main/java/com/clokey/server/domain/member/api/AuthController.java
  src/main/java/com/clokey/server/domain/member/application/AppleAuthService.java
  src/main/java/com/clokey/server/domain/member/application/AppleAuthServiceImpl.java
  src/main/java/com/clokey/server/domain/member/application/AuthServiceImpl.java
  src/main/java/com/clokey/server/domain/member/application/FollowRepositoryService.java
  src/main/java/com/clokey/server/domain/member/application/FollowRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/member/application/MemberRepositoryService.java
  src/main/java/com/clokey/server/domain/member/application/MemberRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/member/application/UnlinkService.java
  src/main/java/com/clokey/server/domain/member/application/UnlinkServiceImpl.java
  src/main/java/com/clokey/server/domain/member/domain/entity/Member.java
  src/main/java/com/clokey/server/domain/member/domain/repository/FollowRepository.java
  src/main/java/com/clokey/server/domain/member/domain/repository/MemberRepository.java
  src/main/java/com/clokey/server/domain/member/dto/AuthDTO.java
  src/main/java/com/clokey/server/domain/member/scheduler/InactiveUserCleanupTask.java
  src/main/java/com/clokey/server/domain/notification/application/NotificationRepositoryService.java
  src/main/java/com/clokey/server/domain/notification/application/NotificationRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/notification/domain/repository/NotificationRepository.java
  src/main/java/com/clokey/server/domain/term/application/MemberTermRepositoryService.java
  src/main/java/com/clokey/server/domain/term/application/MemberTermRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/term/domain/repository/MemberTermRepository.java
  src/main/java/com/clokey/server/global/error/code/status/ErrorStatus.java
  src/main/java/com/clokey/server/global/error/code/status/SuccessStatus.java
Labels: :sparkles: Feat

#217 [refactor/#216] 검색 로직 개선
  src/main/java/com/clokey/server/domain/search/application/SearchRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/search/application/SearchServiceImpl.java
  src/main/resources/static/elastic-mapping.json
  src/main/resources/static/elastic-setting.json
Labels: :recycle: Refactor

#233 [fix/#232] 자기 자신의 회원 프로필 조회 매서드 수정
  src/main/java/com/clokey/server/domain/member/application/GetUserQueryServiceImpl.java
Labels: :fire: Fix

#235 [refactor/#234] 자기 자신에게 알림 보내는 로직 수정
  src/main/java/com/clokey/server/domain/history/application/HistoryServiceImpl.java
  src/main/java/com/clokey/server/domain/notification/application/NotificationServiceImpl.java
Labels: :recycle: Refactor

#231 [refactor/#221] member refactoring
  src/main/java/com/clokey/server/domain/cloth/application/ClothRepositoryService.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/cloth/domain/repository/ClothRepository.java
  src/main/java/com/clokey/server/domain/history/application/HistoryRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/domain/repository/HistoryRepository.java
  src/main/java/com/clokey/server/domain/member/api/AuthController.java
  src/main/java/com/clokey/server/domain/member/api/MemberRestController.java
  src/main/java/com/clokey/server/domain/member/application/AppleAuthService.java
  src/main/java/com/clokey/server/domain/member/application/AppleAuthServiceImpl.java
  src/main/java/com/clokey/server/domain/member/application/AuthService.java
  src/main/java/com/clokey/server/domain/member/application/AuthServiceImpl.java
  src/main/java/com/clokey/server/domain/member/application/FollowCommandService.java
  src/main/java/com/clokey/server/domain/member/application/FollowCommandServiceImpl.java
  src/main/java/com/clokey/server/domain/member/application/FollowRepositoryService.java
  src/main/java/com/clokey/server/domain/member/application/FollowRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/member/application/FollowingService.java
  src/main/java/com/clokey/server/domain/member/application/FollowingServiceImpl.java
  src/main/java/com/clokey/server/domain/member/application/GetUserQueryService.java
  src/main/java/com/clokey/server/domain/member/application/GetUserQueryServiceImpl.java
  src/main/java/com/clokey/server/domain/member/application/IDQueryService.java
  src/main/java/com/clokey/server/domain/member/application/IDQueryServiceImpl.java
  src/main/java/com/clokey/server/domain/member/application/MemberRepositoryService.java
  src/main/java/com/clokey/server/domain/member/application/MemberRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/member/application/MemberService.java
  src/main/java/com/clokey/server/domain/member/application/MemberServiceImpl.java
  src/main/java/com/clokey/server/domain/member/application/ProfileCommandService.java
  src/main/java/com/clokey/server/domain/member/application/ProfileCommandServiceImpl.java
  src/main/java/com/clokey/server/domain/member/application/UnlinkServiceImpl.java
  src/main/java/com/clokey/server/domain/member/domain/entity/Member.java
  src/main/java/com/clokey/server/domain/member/domain/repository/FollowRepository.java
  src/main/java/com/clokey/server/domain/member/domain/repository/MemberRepository.java
  src/main/java/com/clokey/server/domain/member/dto/AuthDTO.java
  src/main/java/com/clokey/server/domain/member/dto/MemberDTO.java
  src/main/java/com/clokey/server/domain/member/exception/annotation/NotFollowMyself.java
  src/main/java/com/clokey/server/domain/member/exception/validator/NotFollowMyselfValidator.java
  src/main/java/com/clokey/server/global/error/code/status/ErrorStatus.java
Labels: :recycle: Refactor

#243 [refactor/#242] 히스토리, 알림 리팩토링 및 새로운 기능 추가
  src/main/java/com/clokey/server/domain/history/api/HistoryRestController.java
  src/main/java/com/clokey/server/domain/history/application/CommentRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/CommentRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HashtagHistoryRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HashtagHistoryRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HashtagRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HashtagRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HistoryClothRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryClothRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HistoryImageRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryImageRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HistoryRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HistoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/MemberLikeRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/MemberLikeRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/converter/HistoryConverter.java
  src/main/java/com/clokey/server/domain/history/domain/entity/Comment.java
  src/main/java/com/clokey/server/domain/history/domain/entity/Hashtag.java
  src/main/java/com/clokey/server/domain/history/domain/entity/HashtagHistory.java
  src/main/java/com/clokey/server/domain/history/domain/entity/History.java
  src/main/java/com/clokey/server/domain/history/domain/entity/HistoryCloth.java
  src/main/java/com/clokey/server/domain/history/domain/entity/HistoryImage.java
  src/main/java/com/clokey/server/domain/history/domain/repository/CommentRepository.java
  src/main/java/com/clokey/server/domain/history/domain/repository/HistoryImageRepository.java
  src/main/java/com/clokey/server/domain/history/domain/repository/MemberLikeRepository.java
  src/main/java/com/clokey/server/domain/history/dto/HistoryResponseDTO.java
  src/main/java/com/clokey/server/domain/history/exception/annotation/CommentContentLength.java
  src/main/java/com/clokey/server/domain/history/exception/annotation/CommentExist.java
  src/main/java/com/clokey/server/domain/history/exception/annotation/HistoryContentLength.java
  src/main/java/com/clokey/server/domain/history/exception/annotation/HistoryDateFormat.java
  src/main/java/com/clokey/server/domain/history/exception/annotation/HistoryExist.java
  src/main/java/com/clokey/server/domain/history/exception/annotation/HistoryImageQuantityLimit.java
  src/main/java/com/clokey/server/domain/history/exception/annotation/MonthFormat.java
  src/main/java/com/clokey/server/domain/history/exception/annotation/ParentCommentConditions.java
  src/main/java/com/clokey/server/domain/history/exception/annotation/UniqueClothes.java
  src/main/java/com/clokey/server/domain/history/exception/annotation/UniqueHashtags.java
  src/main/java/com/clokey/server/domain/history/exception/validator/CommentExistValidator.java
  src/main/java/com/clokey/server/domain/history/exception/validator/HistoryAccessibleValidator.java
  src/main/java/com/clokey/server/domain/history/exception/validator/HistoryContentLengthValidator.java
  src/main/java/com/clokey/server/domain/history/exception/validator/HistoryDateFormatValidator.java
  src/main/java/com/clokey/server/domain/history/exception/validator/HistoryExistValidator.java
  src/main/java/com/clokey/server/domain/history/exception/validator/HistoryImageQuantityLimitValidator.java
  src/main/java/com/clokey/server/domain/history/exception/validator/HistoryLikedValidator.java
  src/main/java/com/clokey/server/domain/history/exception/validator/MonthFormatValidator.java
  src/main/java/com/clokey/server/domain/history/exception/validator/ParentCommentsConditionsValidator.java
  src/main/java/com/clokey/server/domain/member/api/MemberRestController.java
  src/main/java/com/clokey/server/domain/member/application/MemberService.java
  src/main/java/com/clokey/server/domain/member/application/MemberServiceImpl.java
  src/main/java/com/clokey/server/domain/member/domain/entity/Member.java
  src/main/java/com/clokey/server/domain/notification/api/NotificationRestController.java
  src/main/java/com/clokey/server/domain/notification/application/NotificationRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/notification/application/NotificationService.java
  src/main/java/com/clokey/server/domain/notification/application/NotificationServiceImpl.java
  src/main/java/com/clokey/server/domain/notification/converter/NotificationConverter.java
  src/main/java/com/clokey/server/domain/notification/domain/entity/ClokeyNotification.java
  src/main/java/com/clokey/server/domain/notification/dto/NotificationResponseDTO.java
  src/main/java/com/clokey/server/domain/notification/exception/annotation/NotificationExist.java
  src/main/java/com/clokey/server/domain/notification/exception/validator/NotificationExistValidator.java
Labels: :recycle: Refactor

#245 [fix/#244] 오류 수정
  src/main/java/com/clokey/server/domain/cloth/application/ClothRepositoryService.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/cloth/domain/repository/ClothRepository.java
Labels: :fire: Fix

#249 [ fix/#248] 프로필 조회에서 옷에 대한 접근 권한 반영
  src/main/java/com/clokey/server/domain/cloth/application/ClothRepositoryService.java
  src/main/java/com/clokey/server/domain/cloth/application/ClothRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/cloth/domain/repository/ClothRepository.java
  src/main/java/com/clokey/server/domain/member/application/MemberServiceImpl.java
  src/main/java/com/clokey/server/domain/member/converter/GetUserConverter.java
Labels: :fire: Fix

#253 [feat/#252] 모니터링 도구 추가
  build.gradle
  src/main/java/com/clokey/server/global/config/security/SecurityConfig.java
Labels: :sparkles: Feat

#256 [refactor/#237] member refactor
  src/main/java/com/clokey/server/domain/category/api/CategoryRestController.java
  src/main/java/com/clokey/server/domain/category/application/CategoryQueryService.java
  src/main/java/com/clokey/server/domain/category/application/CategoryQueryServiceImpl.java
  src/main/java/com/clokey/server/domain/category/application/CategoryRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/category/application/CategoryService.java
  src/main/java/com/clokey/server/domain/category/application/CategoryServiceImpl.java
  src/main/java/com/clokey/server/domain/category/converter/CategoryConverter.java
  src/main/java/com/clokey/server/domain/member/api/AuthController.java
  src/main/java/com/clokey/server/domain/member/api/MemberRestController.java
  src/main/java/com/clokey/server/domain/member/application/AuthService.java
  src/main/java/com/clokey/server/domain/member/application/AuthServiceImpl.java
  src/main/java/com/clokey/server/domain/member/application/FollowRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/member/application/MemberRepositoryService.java
  src/main/java/com/clokey/server/domain/member/application/MemberRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/member/application/MemberService.java
  src/main/java/com/clokey/server/domain/member/application/MemberServiceImpl.java
  src/main/java/com/clokey/server/domain/member/application/UnlinkServiceImpl.java
  src/main/java/com/clokey/server/domain/member/converter/GetUserConverter.java
  src/main/java/com/clokey/server/domain/member/converter/MemberDocumentConverter.java
  src/main/java/com/clokey/server/domain/member/domain/entity/Member.java
  src/main/java/com/clokey/server/domain/member/domain/repository/FollowRepository.java
  src/main/java/com/clokey/server/domain/member/domain/repository/MemberRepository.java
  src/main/java/com/clokey/server/domain/member/dto/AuthDTO.java
  src/main/java/com/clokey/server/domain/member/dto/MemberDTO.java
  src/main/java/com/clokey/server/domain/member/exception/annotation/EssentialFieldNotNull.java
  src/main/java/com/clokey/server/domain/member/exception/annotation/IdExist.java
  src/main/java/com/clokey/server/domain/member/exception/annotation/IdValid.java
  src/main/java/com/clokey/server/domain/member/exception/annotation/MemberExist.java
  src/main/java/com/clokey/server/domain/member/exception/annotation/NullableClokeyIdExist.java
  src/main/java/com/clokey/server/domain/member/exception/validator/IdValidValidator.java
  src/main/java/com/clokey/server/domain/term/api/TermRestController.java
  src/main/java/com/clokey/server/domain/term/application/MemberTermRepositoryService.java
  src/main/java/com/clokey/server/domain/term/application/MemberTermRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/term/application/TermCommandService.java
  src/main/java/com/clokey/server/domain/term/application/TermCommandServiceImpl.java
  src/main/java/com/clokey/server/domain/term/domain/entity/MemberTerm.java
  src/main/java/com/clokey/server/domain/term/domain/repository/MemberTermRepository.java
  src/main/java/com/clokey/server/domain/term/dto/TermRequestDTO.java
  src/main/java/com/clokey/server/domain/term/exception/annotation/EssentialTermAgree.java
  src/main/java/com/clokey/server/domain/term/exception/annotation/InvalidTermId.java
Labels: :recycle: Refactor

#261 [refactor/#237] member refactor
  src/main/java/com/clokey/server/domain/member/application/AuthServiceImpl.java
Labels: :recycle: Refactor

#262 [refactor/#237] device token 유니크 조건 해제
  src/main/java/com/clokey/server/domain/member/domain/entity/Member.java
Labels: :recycle: Refactor

#263 [refactor/#260] 최종 리팩토링
  build.gradle
  src/main/java/com/clokey/server/domain/history/application/HashtagHistoryRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HistoryImageRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/application/HistoryServiceImpl.java
  src/main/java/com/clokey/server/domain/notification/application/NotificationServiceImpl.java
  src/main/java/com/clokey/server/domain/notification/dto/NotificationResponseDTO.java
Labels: :recycle: Refactor

#265 [refactor/#225] 검색 로직 수정 및 스마트요약 API 수정
  src/main/java/com/clokey/server/domain/cloth/application/ClothServiceImpl.java
  src/main/java/com/clokey/server/domain/cloth/converter/ClothConverter.java
  src/main/java/com/clokey/server/domain/cloth/domain/document/ClothDocument.java
  src/main/java/com/clokey/server/domain/cloth/domain/repository/ClothRepository.java
  src/main/java/com/clokey/server/domain/cloth/dto/ClothResponseDTO.java
  src/main/java/com/clokey/server/domain/history/domain/document/HistoryDocument.java
  src/main/java/com/clokey/server/domain/member/domain/document/MemberDocument.java
  src/main/java/com/clokey/server/domain/search/application/SearchServiceImpl.java
  src/main/resources/static/elastic-mapping-cloth.json
  src/main/resources/static/elastic-mapping-history.json
  src/main/resources/static/elastic-mapping-member.json
  src/main/resources/static/elastic-mapping.json
  src/main/resources/static/elastic-setting-cloth.json
  src/main/resources/static/elastic-setting-history.json
  src/main/resources/static/elastic-setting-member.json
Labels: :recycle: Refactor

#270 [fix/#225] 해시태그 검색 로직 개선
  src/main/java/com/clokey/server/domain/search/application/SearchServiceImpl.java
Labels: :recycle: Refactor

#273 [refactor/#258] folder, home api 리팩토링
  src/main/java/com/clokey/server/domain/category/application/CategoryServiceImpl.java
  src/main/java/com/clokey/server/domain/folder/application/ClothFolderRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/folder/application/FolderRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/folder/application/FolderServiceImpl.java
  src/main/java/com/clokey/server/domain/folder/domain/repository/ClothFolderRepository.java
  src/main/java/com/clokey/server/domain/folder/domain/repository/FolderRepository.java
  src/main/java/com/clokey/server/domain/history/application/HistoryRepositoryService.java
  src/main/java/com/clokey/server/domain/history/application/HistoryRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/history/domain/repository/HashtagHistoryRepository.java
  src/main/java/com/clokey/server/domain/history/domain/repository/HistoryRepository.java
  src/main/java/com/clokey/server/domain/member/application/FollowRepositoryService.java
  src/main/java/com/clokey/server/domain/member/application/FollowRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/member/domain/repository/FollowRepository.java
  src/main/java/com/clokey/server/domain/recommendation/application/RecommendationServiceImpl.java
  src/main/java/com/clokey/server/domain/recommendation/converter/RecommendationConverter.java
  src/main/java/com/clokey/server/domain/recommendation/dto/RecommendationResponseDTO.java
  src/main/java/com/clokey/server/domain/recommendation/exception/annotation/CheckTemperature.java
  src/main/java/com/clokey/server/global/error/code/status/ErrorStatus.java
Labels: :sparkles: Feat, :recycle: Refactor

#275 [refactor/#225] 검색 로직 완전 마지막 수정이고 싶다..
  src/main/java/com/clokey/server/domain/member/application/FollowRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/recommendation/application/RecommendationServiceImpl.java
  src/main/java/com/clokey/server/domain/search/application/SearchServiceImpl.java
Labels: :fire: Fix

#276 [fix/#274] 다른계정 가입 가능 변경
  src/main/java/com/clokey/server/domain/member/application/AuthServiceImpl.java
Labels: :fire: Fix

#278 [refactor/#277] login 수정
  src/main/java/com/clokey/server/domain/member/application/AuthServiceImpl.java
  src/main/java/com/clokey/server/domain/member/application/MemberRepositoryService.java
  src/main/java/com/clokey/server/domain/member/application/MemberRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/member/domain/entity/Member.java
  src/main/java/com/clokey/server/domain/member/domain/repository/MemberRepository.java
Labels: :recycle: Refactor

#280 [refactor/#279] 로그인 api 수정
  src/main/java/com/clokey/server/domain/member/application/AuthServiceImpl.java
  src/main/java/com/clokey/server/domain/member/application/MemberRepositoryService.java
  src/main/java/com/clokey/server/domain/member/application/MemberRepositoryServiceImpl.java
  src/main/java/com/clokey/server/domain/member/domain/repository/MemberRepository.java
Labels: :recycle: Refactor

#282 [refactor/#281] notification 수정
  src/main/java/com/clokey/server/domain/folder/application/FolderServiceImpl.java
  src/main/java/com/clokey/server/domain/notification/application/NotificationServiceImpl.java
Labels: :fire: Fix, :recycle: Refactor

#283 [fix/#225] 검색 페이지네이션 오류 수정
  src/main/java/com/clokey/server/domain/cloth/domain/entity/Cloth.java
  src/main/java/com/clokey/server/domain/search/application/SearchServiceImpl.java
Labels: :fire: Fix
